# Generated by Django 5.2.1 on 2026-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('environment_url', models.URLField(unique=True)),
                ('tenant_id', models.CharField(blank=True, max_length=120)),
                ('environment_type', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=32)),
                ('api_token', models.CharField(max_length=255)),
                ('platform_token', models.CharField(blank=True, max_length=255)),
                ('account_uuid', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
