# Generated by Django 5.2.1 on 2026-05-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_name', models.SlugField(max_length=120, unique=True)),
                ('state_path', models.CharField(blank=True, max_length=255)),
                ('last_command', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('plan_running', 'Plan running'), ('apply_running', 'Apply running'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terraform_workspace', to='environments.environment')),
            ],
            options={
                'ordering': ['workspace_name'],
            },
        ),
    ]
