# Generated by Django 5.2.1 on 2026-05-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformworkspace',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('init_running', 'Init running'), ('plan_running', 'Plan running'), ('apply_running', 'Apply running'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='TerraformExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command', models.CharField(choices=[('init', 'Init'), ('plan', 'Plan')], max_length=16)),
                ('exit_code', models.IntegerField()),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='terraform_engine.terraformworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
