# Generated by Django 5.2.1 on 2026-05-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('terraform_engine', '0002_alter_terraformworkspace_status_terraformexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformworkspace',
            name='scope',
            field=models.CharField(choices=[('account_management', 'Account Management'), ('environment', 'Environment'), ('platform', 'Platform')], default='environment', max_length=32),
        ),
        migrations.AlterField(
            model_name='terraformworkspace',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terraform_workspaces', to='environments.environment'),
        ),
    ]
