resource "dynatrace_document" "DPS_Infrastructure_Monitoring" {
  name    = "DPS Infrastructure Monitoring"
  type    = "notebook"
  content = jsonencode({
      "defaultSegments": [],
      "defaultTimeframe": {
        "from": "now()-2h",
        "to": "now()"
      },
      "sections": [
        {
          "id": "7b78e038-06d8-4f2d-8b1f-7294fe936b3a",
          "markdown": "# Infrastructure Monitoring",
          "type": "markdown"
        },
        {
          "drilldownPath": [],
          "filterSegments": [],
          "id": "21b07184-72bb-4975-8355-044b9e4a9753",
          "previousFilterSegments": [],
          "showInput": true,
          "showTitle": true,
          "state": {
            "davis": {
              "davisVisualization": {
                "isAvailable": true
              },
              "includeLogs": true
            },
            "input": {
              "timeframe": {
                "from": "2025-07-08T08:14:00.000Z",
                "to": "2025-08-07T08:14:00.000Z"
              },
              "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| makeTimeseries total_billed_usage = sum(billed_host_hours), interval: 24h, time: usage.start"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-08-07T08:15:23.817Z",
              "input": {
                "timeframe": {
                  "from": "2025-07-08T08:14:00.000Z",
                  "to": "2025-08-07T08:14:00.000Z"
                },
                "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| makeTimeseries total_billed_usage = sum(billed_host_hours), interval: 24h, time: usage.start"
              },
              "notifications": [],
              "querySettings": {
                "defaultSamplingRatio": 10,
                "defaultScanLimitGbytes": 500,
                "enableSampling": false,
                "maxResultMegaBytes": 1,
                "maxResultRecords": 1000
              },
              "value": {
                "metadata": {
                  "grail": {
                    "analysisTimeframe": {
                      "end": "2025-08-07T08:14:00.000000000Z",
                      "start": "2025-07-08T08:14:00.000000000Z"
                    },
                    "canonicalQuery": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" AND event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| makeTimeseries interval:24h, time:usage.start, total_billed_usage = sum(billed_host_hours)",
                    "dqlVersion": "V1_0",
                    "executionTimeMilliseconds": 1067,
                    "locale": "de",
                    "notifications": [],
                    "query": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| makeTimeseries total_billed_usage = sum(billed_host_hours), interval: 24h, time: usage.start",
                    "queryId": "e3f4ea76-38b6-4a57-8850-14261266634f",
                    "sampled": false,
                    "scannedBytes": 0,
                    "scannedDataPoints": 0,
                    "scannedRecords": 0,
                    "timezone": "Europe/Vienna"
                  }
                },
                "records": [
                  {
                    "interval": "86400000000000",
                    "timeframe": {
                      "end": "2025-08-08T00:00:00.000000000+02:00",
                      "start": "2025-07-08T00:00:00.000000000+02:00"
                    },
                    "total_billed_usage": [
                      280,
                      480,
                      508,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      528,
                      541.5,
                      552,
                      552,
                      589.5,
                      639.75,
                      648,
                      648,
                      648,
                      648,
                      648,
                      639.5,
                      625,
                      624,
                      260
                    ]
                  }
                ],
                "types": [
                  {
                    "indexRange": [
                      0,
                      0
                    ],
                    "mappings": {
                      "interval": {
                        "type": "duration"
                      },
                      "timeframe": {
                        "type": "timeframe"
                      },
                      "total_billed_usage": {
                        "type": "array",
                        "types": [
                          {
                            "indexRange": [
                              0,
                              30
                            ],
                            "mappings": {
                              "element": {
                                "type": "double"
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            },
            "state": "success",
            "visualization": "barChart",
            "visualizationSettings": {
              "autoSelectVisualization": false,
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "fieldMapping": {
                  "leftAxisValues": [
                    "total_billed_usage"
                  ],
                  "timestamp": "timeframe"
                },
                "gapPolicy": "gap",
                "hiddenLegendFields": [
                  "billed_gibibyte_hours"
                ],
                "leftYAxisSettings": {
                  "isLabelVisible": true,
                  "label": "Billed Host Hours"
                },
                "pointsDisplay": "auto",
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisIsLabelVisible": false,
                "xAxisLabel": "timeframe",
                "xAxisScaling": "auto"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "categorical",
                "dataMappings": {},
                "displayedFields": [],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "",
                "prefixIcon": "AnalyticsIcon",
                "showLabel": true
              },
              "table": {
                "columnOrder": [
                  "[\"timeframe\",\"start\"]",
                  "[\"timeframe\",\"end\"]",
                  "[\"interval\"]",
                  "[\"total_billed_usage\"]"
                ],
                "columnTypeOverrides": [
                  {
                    "fields": [
                      "total_billed_usage"
                    ],
                    "id": 1754554523817,
                    "value": "sparkline"
                  }
                ],
                "columnWidths": {},
                "enableSparklines": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "title": "Overview - Total usage billed per day",
          "type": "dql"
        },
        {
          "drilldownPath": [],
          "filterSegments": [],
          "id": "70c30527-f671-43e3-a4bd-eb275916c82f",
          "previousFilterSegments": [],
          "showInput": true,
          "showTitle": true,
          "state": {
            "davis": {
              "davisVisualization": {
                "isAvailable": true
              },
              "includeLogs": true
            },
            "input": {
              "timeframe": {
                "from": "2025-07-08T08:14:00.000Z",
                "to": "2025-08-07T08:14:00.000Z"
              },
              "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| summarize billed_hours = sum(billed_host_hours), by:{dt.entity.host}\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_hours\n| sort billed_hours DESC"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-08-07T08:15:23.676Z",
              "input": {
                "timeframe": {
                  "from": "2025-07-08T08:14:00.000Z",
                  "to": "2025-08-07T08:14:00.000Z"
                },
                "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| summarize billed_hours = sum(billed_host_hours), by:{dt.entity.host}\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_hours\n| sort billed_hours DESC"
              },
              "notifications": [],
              "querySettings": {
                "defaultSamplingRatio": 10,
                "defaultScanLimitGbytes": 500,
                "enableSampling": false,
                "maxResultMegaBytes": 1,
                "maxResultRecords": 1000
              },
              "value": {
                "metadata": {
                  "grail": {
                    "analysisTimeframe": {
                      "end": "2025-08-07T08:14:00.000000000Z",
                      "start": "2025-07-08T08:14:00.000000000Z"
                    },
                    "canonicalQuery": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" AND event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| summarize by:{dt.entity.host}, billed_hours = sum(billed_host_hours)\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_hours\n| sort billed_hours desc",
                    "dqlVersion": "V1_0",
                    "executionTimeMilliseconds": 1226,
                    "locale": "de",
                    "notifications": [],
                    "query": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| summarize billed_hours = sum(billed_host_hours), by:{dt.entity.host}\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_hours\n| sort billed_hours DESC",
                    "queryId": "68d92eef-99d6-45cc-9257-0df1411fe87f",
                    "sampled": false,
                    "scannedBytes": 0,
                    "scannedDataPoints": 0,
                    "scannedRecords": 32,
                    "timezone": "Europe/Vienna"
                  }
                },
                "records": [
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-0C1384E1E6716F46",
                    "host_name": "2217psm0010p08.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-17236FB4AA53B7FE",
                    "host_name": "2217htmg0469p01"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-280962E09A43F01D",
                    "host_name": "2217psm0010p12.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-2C4A33F1CACE2727",
                    "host_name": "2217htmg0469p02"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-30A4824A919B88C2",
                    "host_name": "2217PSMP0010P01.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-3565708D47127D40",
                    "host_name": "2217psm0010p11.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-3DDE976CD5D7D916",
                    "host_name": "2217cpm0010p01.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-46C5336F4E641280",
                    "host_name": "2217DBSQLCLN01.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-590FBA98DC044D15",
                    "host_name": "2217psm0010p05.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-71B241CBCAEF6EE2",
                    "host_name": "2217PSMP0010P02.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-72E43AAACC9059B9",
                    "host_name": "2217psm0010p04.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-749DBF577FB57CD4",
                    "host_name": "2217psm0010p01.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-78D9080824662889",
                    "host_name": "2217psm0010p03.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-819525E7E9A6D71F",
                    "host_name": "2217psm0467p01"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-91D52EF0321D54B9",
                    "host_name": "2217psm0010p06.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-C16793303764302D",
                    "host_name": "2217DBSQLCLN02.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-C9B7467795DA185C",
                    "host_name": "2217psm0010p02.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-D99903D58C348261",
                    "host_name": "2217psm0010p07.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-ECA5AA097ACC20C5",
                    "host_name": "2217PSM0468P01"
                  },
                  {
                    "billed_hours": 720,
                    "host_id": "HOST-EFD88A91BFA12D4E",
                    "host_name": "2217DBSQLCLN03.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 672,
                    "host_id": "HOST-5B144D92C902184E",
                    "host_name": "2217dbxecmn01.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 672,
                    "host_id": "HOST-E606C497EB1200CA",
                    "host_name": "2217dbxecmn02.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 242.5,
                    "host_id": "HOST-6BD2753C31A41D45",
                    "host_name": "2217cx0010wei00.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 192.75,
                    "host_id": "HOST-6005A107F6747B45",
                    "host_name": "2217cx0010wei51.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 192.75,
                    "host_id": "HOST-DECBE055C4792799",
                    "host_name": "2217cx0010wei53.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 167.75,
                    "host_id": "HOST-5C8D9CD7B1758458",
                    "host_name": "2217cx0010wei50.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 167.75,
                    "host_id": "HOST-D7B07386A22740BA",
                    "host_name": "2217cx0010wei52.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 50,
                    "host_id": "HOST-4949F00F96A3F48C",
                    "host_name": "2217cx0010wei52.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 50,
                    "host_id": "HOST-CDB357A889421A96",
                    "host_name": "2217cx0010wei50.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 46,
                    "host_id": "HOST-7EC52369CEB52B4E",
                    "host_name": "2217cx0010wei51.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 46,
                    "host_id": "HOST-C085023E79309474",
                    "host_name": "2217cx0010wei53.voestalpine.root.local"
                  },
                  {
                    "billed_hours": 23.75,
                    "host_id": "HOST-479F52F09BFE393A",
                    "host_name": "2217cx0010wei52.voestalpine.root.local"
                  }
                ],
                "types": [
                  {
                    "indexRange": [
                      0,
                      31
                    ],
                    "mappings": {
                      "billed_hours": {
                        "type": "double"
                      },
                      "host_id": {
                        "type": "string"
                      },
                      "host_name": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            },
            "state": "success",
            "visualization": "table",
            "visualizationSettings": {
              "autoSelectVisualization": false,
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisLabel": "dt.entity.host",
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "tooltipVariant": "single",
                  "valueAxisLabel": "events_of_host",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "gapPolicy": "gap",
                "hiddenLegendFields": [
                  "billed_gibibyte_hours"
                ],
                "leftYAxisSettings": {},
                "pointsDisplay": "auto",
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisIsLabelVisible": false,
                "xAxisLabel": "timestamp",
                "xAxisScaling": "auto"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "blue",
                "dataMappings": {
                  "value": "events_of_host"
                },
                "displayedFields": [
                  "dt.entity.host"
                ],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "events_of_host",
                "prefixIcon": "AnalyticsIcon",
                "recordField": "events_of_host",
                "showLabel": true,
                "sparklineSettings": {},
                "trend": {
                  "isVisible": true,
                  "trendType": "auto"
                }
              },
              "table": {
                "columnOrder": [
                  "[\"host_id\"]",
                  "[\"host_name\"]",
                  "[\"billed_hours\"]"
                ],
                "columnTypeOverrides": [],
                "columnWidths": {},
                "enableSparklines": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "title": "Overview - Total usage per host",
          "type": "dql"
        },
        {
          "drilldownPath": [],
          "filterSegments": [],
          "id": "7e5588d6-cd66-4321-a9d9-20443f135555",
          "previousFilterSegments": [],
          "showInput": true,
          "showTitle": true,
          "state": {
            "davis": {
              "davisVisualization": {
                "isAvailable": true
              },
              "includeLogs": true
            },
            "input": {
              "timeframe": {
                "from": "2025-07-08T08:14:00.000Z",
                "to": "2025-08-07T08:14:00.000Z"
              },
              "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_host_hours)\n| filter billed_host_hours \u003e 0\n| makeTimeseries host_count = countDistinct(dt.entity.host), interval: 15m, time: usage.start"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-08-07T08:15:23.375Z",
              "input": {
                "timeframe": {
                  "from": "2025-07-08T08:14:00.000Z",
                  "to": "2025-08-07T08:14:00.000Z"
                },
                "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_host_hours)\n| filter billed_host_hours \u003e 0\n| makeTimeseries host_count = countDistinct(dt.entity.host), interval: 15m, time: usage.start"
              },
              "notifications": [],
              "querySettings": {
                "defaultSamplingRatio": 10,
                "defaultScanLimitGbytes": 500,
                "enableSampling": false,
                "maxResultMegaBytes": 1,
                "maxResultRecords": 1000
              },
              "value": {
                "metadata": {
                  "grail": {
                    "analysisTimeframe": {
                      "end": "2025-08-07T08:14:00.000000000Z",
                      "start": "2025-07-08T08:14:00.000000000Z"
                    },
                    "canonicalQuery": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" AND event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_host_hours)\n| filter billed_host_hours \u003e 0\n| makeTimeseries interval:15m, time:usage.start, host_count = countDistinct(dt.entity.host)",
                    "dqlVersion": "V1_0",
                    "executionTimeMilliseconds": 1124,
                    "locale": "de",
                    "notifications": [],
                    "query": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Infrastructure Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_host_hours)\n| filter billed_host_hours \u003e 0\n| makeTimeseries host_count = countDistinct(dt.entity.host), interval: 15m, time: usage.start",
                    "queryId": "0e03ff88-ff29-4079-b9d4-0a3c87ac0298",
                    "sampled": false,
                    "scannedBytes": 0,
                    "scannedDataPoints": 0,
                    "scannedRecords": 0,
                    "timezone": "Europe/Vienna"
                  }
                },
                "records": [
                  {
                    "host_count": [
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      22,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      23,
                      22,
                      23,
                      23,
                      23,
                      24,
                      24,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      28,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      27,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      28,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      28,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      26,
                      null
                    ],
                    "interval": "1800000000000",
                    "timeframe": {
                      "end": "2025-08-07T10:30:00.000000000+02:00",
                      "start": "2025-07-08T10:00:00.000000000+02:00"
                    }
                  }
                ],
                "types": [
                  {
                    "indexRange": [
                      0,
                      0
                    ],
                    "mappings": {
                      "host_count": {
                        "type": "array",
                        "types": [
                          {
                            "indexRange": [
                              0,
                              1440
                            ],
                            "mappings": {
                              "element": {
                                "type": "double"
                              }
                            }
                          }
                        ]
                      },
                      "interval": {
                        "type": "duration"
                      },
                      "timeframe": {
                        "type": "timeframe"
                      }
                    }
                  }
                ]
              }
            },
            "state": "success",
            "visualization": "lineChart",
            "visualizationSettings": {
              "autoSelectVisualization": false,
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "fieldMapping": {
                  "leftAxisValues": [
                    "host_count"
                  ],
                  "timestamp": "timeframe"
                },
                "gapPolicy": "gap",
                "hiddenLegendFields": [
                  "billed_gibibyte_hours"
                ],
                "leftYAxisSettings": {
                  "isLabelVisible": true,
                  "label": "Billed Hosts"
                },
                "pointsDisplay": "auto",
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisIsLabelVisible": false,
                "xAxisLabel": "timeframe",
                "xAxisScaling": "auto"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "categorical",
                "dataMappings": {},
                "displayedFields": [],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "total_hosts",
                "prefixIcon": "AnalyticsIcon",
                "recordField": "total_billed_hosts",
                "showLabel": true,
                "sparklineSettings": {
                  "record": "host_count"
                },
                "trend": {
                  "isVisible": true,
                  "trendType": "auto"
                }
              },
              "table": {
                "columnTypeOverrides": [
                  {
                    "fields": [
                      "host_count"
                    ],
                    "id": 1744705995525,
                    "value": "sparkline"
                  }
                ],
                "columnWidths": {},
                "enableSparklines": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "title": "Overview - Number of billed hosts",
          "type": "dql"
        }
      ],
      "version": "7"
    })
  private = true
}
