resource "dynatrace_document" "DPS_Full-Stack_Monitoring" {
  name    = "DPS Full-Stack Monitoring"
  type    = "notebook"
  content = jsonencode({
      "defaultSegments": [],
      "defaultTimeframe": {
        "from": "now()-2h",
        "to": "now()"
      },
      "sections": [
        {
          "id": "db1babfa-4f7c-43fd-a0cb-b2143772cd81",
          "markdown": "# Full-Stack Monitoring",
          "type": "markdown"
        },
        {
          "drilldownPath": [],
          "filterSegments": [],
          "id": "ceff6d9f-a0ba-499b-8db0-175cef09087d",
          "previousFilterSegments": [],
          "showInput": true,
          "showTitle": true,
          "state": {
            "davis": {
              "davisVisualization": {
                "isAvailable": true
              },
              "includeLogs": true
            },
            "input": {
              "timeframe": {
                "from": "2025-07-08T08:13:00.000Z",
                "to": "2025-08-07T08:13:00.000Z"
              },
              "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| makeTimeseries total_billed_usage = sum(billed_gibibyte_hours), interval: 24h, time: usage.start"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-08-07T08:14:23.595Z",
              "input": {
                "timeframe": {
                  "from": "2025-07-08T08:13:00.000Z",
                  "to": "2025-08-07T08:13:00.000Z"
                },
                "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| makeTimeseries total_billed_usage = sum(billed_gibibyte_hours), interval: 24h, time: usage.start"
              },
              "notifications": [],
              "querySettings": {
                "defaultSamplingRatio": 10,
                "defaultScanLimitGbytes": 500,
                "enableSampling": false,
                "maxResultMegaBytes": 1,
                "maxResultRecords": 1000
              },
              "value": {
                "metadata": {
                  "grail": {
                    "analysisTimeframe": {
                      "end": "2025-08-07T08:13:00.000000000Z",
                      "start": "2025-07-08T08:13:00.000000000Z"
                    },
                    "canonicalQuery": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" AND event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| makeTimeseries interval:24h, time:usage.start, total_billed_usage = sum(billed_gibibyte_hours)",
                    "dqlVersion": "V1_0",
                    "executionTimeMilliseconds": 1036,
                    "locale": "de",
                    "notifications": [],
                    "query": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| makeTimeseries total_billed_usage = sum(billed_gibibyte_hours), interval: 24h, time: usage.start",
                    "queryId": "8e246669-889e-4ffc-920f-4f87127f99e5",
                    "sampled": false,
                    "scannedBytes": 0,
                    "scannedDataPoints": 0,
                    "scannedRecords": 0,
                    "timezone": "Europe/Vienna"
                  }
                },
                "records": [
                  {
                    "interval": "86400000000000",
                    "timeframe": {
                      "end": "2025-08-08T00:00:00.000000000+02:00",
                      "start": "2025-07-08T00:00:00.000000000+02:00"
                    },
                    "total_billed_usage": [
                      13996.5,
                      23873.875,
                      24319.875,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23848,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      23808,
                      9920
                    ]
                  }
                ],
                "types": [
                  {
                    "indexRange": [
                      0,
                      0
                    ],
                    "mappings": {
                      "interval": {
                        "type": "duration"
                      },
                      "timeframe": {
                        "type": "timeframe"
                      },
                      "total_billed_usage": {
                        "type": "array",
                        "types": [
                          {
                            "indexRange": [
                              0,
                              30
                            ],
                            "mappings": {
                              "element": {
                                "type": "double"
                              }
                            }
                          }
                        ]
                      }
                    }
                  }
                ]
              }
            },
            "state": "success",
            "visualization": "barChart",
            "visualizationSettings": {
              "autoSelectVisualization": false,
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisLabel": "interval",
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "tooltipVariant": "single",
                  "valueAxisLabel": "interval",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "fieldMapping": {
                  "leftAxisValues": [
                    "total_billed_usage"
                  ],
                  "timestamp": "timeframe"
                },
                "gapPolicy": "gap",
                "hiddenLegendFields": [
                  "billed_gibibyte_hours"
                ],
                "leftYAxisSettings": {
                  "isLabelVisible": true,
                  "label": "Billed Gigibyte Hours"
                },
                "pointsDisplay": "auto",
                "seriesOverrides": [],
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisIsLabelVisible": false,
                "xAxisLabel": "timeframe",
                "xAxisScaling": "auto"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "categorical",
                "dataMappings": {},
                "displayedFields": [],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "",
                "prefixIcon": "AnalyticsIcon",
                "showLabel": true
              },
              "table": {
                "columnOrder": [
                  "[\"total_billed_usage\"]",
                  "[\"timeframe\",\"start\"]",
                  "[\"timeframe\",\"end\"]",
                  "[\"interval\"]"
                ],
                "columnTypeOverrides": [
                  {
                    "fields": [
                      "total_billed_usage"
                    ],
                    "id": 1744190300879,
                    "value": "sparkline"
                  }
                ],
                "columnWidths": {},
                "enableSparklines": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "title": "Overview - Total usage billed per day",
          "type": "dql"
        },
        {
          "drilldownPath": [],
          "filterSegments": [],
          "id": "58d11a7f-4148-4838-a0bf-8ea6106d8f23",
          "previousFilterSegments": [],
          "showInput": true,
          "showTitle": true,
          "state": {
            "davis": {
              "davisVisualization": {
                "isAvailable": true
              },
              "includeLogs": true
            },
            "input": {
              "timeframe": {
                "from": "2025-07-08T08:13:00.000Z",
                "to": "2025-08-07T08:13:00.000Z"
              },
              "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| summarize billed_gibibyte = sum(billed_gibibyte_hours), by:{dt.entity.host}\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_gibibyte\n| sort billed_gibibyte DESC"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-08-07T08:14:23.978Z",
              "input": {
                "timeframe": {
                  "from": "2025-07-08T08:13:00.000Z",
                  "to": "2025-08-07T08:13:00.000Z"
                },
                "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| summarize billed_gibibyte = sum(billed_gibibyte_hours), by:{dt.entity.host}\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_gibibyte\n| sort billed_gibibyte DESC"
              },
              "notifications": [],
              "querySettings": {
                "defaultSamplingRatio": 10,
                "defaultScanLimitGbytes": 500,
                "enableSampling": false,
                "maxResultMegaBytes": 1,
                "maxResultRecords": 1000
              },
              "value": {
                "metadata": {
                  "grail": {
                    "analysisTimeframe": {
                      "end": "2025-08-07T08:13:00.000000000Z",
                      "start": "2025-07-08T08:13:00.000000000Z"
                    },
                    "canonicalQuery": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" AND event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| summarize by:{dt.entity.host}, billed_gibibyte = sum(billed_gibibyte_hours)\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_gibibyte\n| sort billed_gibibyte desc",
                    "dqlVersion": "V1_0",
                    "executionTimeMilliseconds": 1071,
                    "locale": "de",
                    "notifications": [],
                    "query": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| summarize billed_gibibyte = sum(billed_gibibyte_hours), by:{dt.entity.host}\n| fields host_id = dt.entity.host, host_name = entityAttr(dt.entity.host, \"entity.name\"), billed_gibibyte\n| sort billed_gibibyte DESC",
                    "queryId": "f1c1006b-aadb-4c1a-b931-41bec69a5205",
                    "sampled": false,
                    "scannedBytes": 0,
                    "scannedDataPoints": 0,
                    "scannedRecords": 24,
                    "timezone": "Europe/Vienna"
                  }
                },
                "records": [
                  {
                    "billed_gibibyte": 95040,
                    "host_id": "HOST-48D8D0E1FD5ADEE0",
                    "host_name": "2236asecmcsb1p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 92160,
                    "host_id": "HOST-05975D427629204E",
                    "host_name": "2236asecmcsb5p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 92160,
                    "host_id": "HOST-E35D35EA4ACC0205",
                    "host_name": "2236asecmcsb3p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 72000,
                    "host_id": "HOST-F6F1B7F770E87E4A",
                    "host_name": "2236asecmcsb4p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 57600,
                    "host_id": "HOST-3CA4B7A9D088C7AA",
                    "host_name": "2236asecmcsf5p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 46080,
                    "host_id": "HOST-B6160E5D2C2AC281",
                    "host_name": "2236asecmcsb2p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 34560,
                    "host_id": "HOST-64FAE88DC89F082C",
                    "host_name": "2217asbee4it01.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-18293E2C2566BC1D",
                    "host_name": "2236asecmds1p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-3C172C4602EBA72A",
                    "host_name": "2236asecmawgp.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-3F364FD91594BE69",
                    "host_name": "2236asecmcsf1p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-64D980053A652A7C",
                    "host_name": "2236asecmds2p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-78653E05D05E6DE6",
                    "host_name": "2236asecmcsf4p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-8DFA23544E33506F",
                    "host_name": "2236asecmblzp.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-C78D0C795A45AFBC",
                    "host_name": "2236asecmcsf3p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 23040,
                    "host_id": "HOST-DF1BC83C6F109665",
                    "host_name": "2236asecmcsf2p.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 11520,
                    "host_id": "HOST-2E1E5993E8E82C23",
                    "host_name": "2236asecmasp.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 11520,
                    "host_id": "HOST-3B354B5980F04E11",
                    "host_name": "2236asmonitor01.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 5760,
                    "host_id": "HOST-9DB0A2461301B6C2",
                    "host_name": "2217pvwa0469p02"
                  },
                  {
                    "billed_gibibyte": 5760,
                    "host_id": "HOST-BE1FFB89AC1B2202",
                    "host_name": "2236asmgnt02.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 5760,
                    "host_id": "HOST-D2574E2AD91F2AA9",
                    "host_name": "2217pvwa0469p01"
                  },
                  {
                    "billed_gibibyte": 255.9375,
                    "host_id": "HOST-5B144D92C902184E",
                    "host_name": "2217dbxecmn01.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 255.9375,
                    "host_id": "HOST-E606C497EB1200CA",
                    "host_name": "2217dbxecmn02.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 174.375,
                    "host_id": "HOST-69A7A24E56F175AB",
                    "host_name": "2217PC63936.voestalpine.root.local"
                  },
                  {
                    "billed_gibibyte": 40,
                    "host_id": "HOST-6BD2753C31A41D45",
                    "host_name": "2217cx0010wei00.voestalpine.root.local"
                  }
                ],
                "types": [
                  {
                    "indexRange": [
                      0,
                      23
                    ],
                    "mappings": {
                      "billed_gibibyte": {
                        "type": "double"
                      },
                      "host_id": {
                        "type": "string"
                      },
                      "host_name": {
                        "type": "string"
                      }
                    }
                  }
                ]
              }
            },
            "state": "success",
            "visualization": "table",
            "visualizationSettings": {
              "autoSelectVisualization": false,
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisLabel": "dt.entity.host",
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "tooltipVariant": "single",
                  "valueAxisLabel": "billed_gibibyte",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "gapPolicy": "gap",
                "hiddenLegendFields": [
                  "billed_gibibyte_hours"
                ],
                "leftYAxisSettings": {},
                "legend": {
                  "hidden": false,
                  "position": "auto"
                },
                "pointsDisplay": "auto",
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisIsLabelVisible": false,
                "xAxisLabel": "timestamp",
                "xAxisScaling": "auto"
              },
              "dataMapping": {
                "value": "billed_gibibyte"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "blue",
                "dataMappings": {
                  "value": "events_of_host"
                },
                "displayedFields": [
                  "dt.entity.host"
                ],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "label": {
                "label": "billed_gibibyte",
                "showLabel": true
              },
              "legend": {
                "position": "auto",
                "ratio": 12,
                "showLegend": false
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "events_of_host",
                "prefixIcon": "AnalyticsIcon",
                "recordField": "events_of_host",
                "showLabel": true,
                "sparklineSettings": {},
                "trend": {
                  "isVisible": true,
                  "trendType": "auto"
                }
              },
              "table": {
                "columnOrder": [
                  "[\"billed_gibibyte\"]",
                  "[\"host_id\"]",
                  "[\"host_name\"]"
                ],
                "columnTypeOverrides": [],
                "columnWidths": {
                  "[\"billed_gibibyte\"]": 105.828125,
                  "[\"entity.name\"]": 132.33,
                  "[\"lookup.entity.name\"]": 289
                },
                "enableSparklines": false,
                "enableThresholdInRow": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [
                  [
                    "host_id"
                  ],
                  [
                    "host_name"
                  ],
                  [
                    "billed_gibibyte"
                  ]
                ],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "title": "Overview - Total usage per host",
          "type": "dql"
        },
        {
          "drilldownPath": [],
          "filterSegments": [],
          "id": "dc05aff1-5a48-4025-962c-a3fa211e0b0d",
          "previousFilterSegments": [],
          "showInput": true,
          "showTitle": true,
          "state": {
            "davis": {
              "davisVisualization": {
                "isAvailable": true
              },
              "includeLogs": true
            },
            "input": {
              "timeframe": {
                "from": "2025-07-08T08:13:00.000Z",
                "to": "2025-08-07T08:13:00.000Z"
              },
              "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_gibibyte_hours)\n| filter billed_gibibyte_hours \u003e 0\n| makeTimeseries host_count = countDistinct(dt.entity.host), interval: 15m, time: usage.start"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-08-07T08:14:23.915Z",
              "input": {
                "timeframe": {
                  "from": "2025-07-08T08:13:00.000Z",
                  "to": "2025-08-07T08:13:00.000Z"
                },
                "value": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_gibibyte_hours)\n| filter billed_gibibyte_hours \u003e 0\n| makeTimeseries host_count = countDistinct(dt.entity.host), interval: 15m, time: usage.start"
              },
              "notifications": [],
              "querySettings": {
                "defaultSamplingRatio": 10,
                "defaultScanLimitGbytes": 500,
                "enableSampling": false,
                "maxResultMegaBytes": 1,
                "maxResultRecords": 1000
              },
              "value": {
                "metadata": {
                  "grail": {
                    "analysisTimeframe": {
                      "end": "2025-08-07T08:13:00.000000000Z",
                      "start": "2025-07-08T08:13:00.000000000Z"
                    },
                    "canonicalQuery": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" AND event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_gibibyte_hours)\n| filter billed_gibibyte_hours \u003e 0\n| makeTimeseries interval:15m, time:usage.start, host_count = countDistinct(dt.entity.host)",
                    "dqlVersion": "V1_0",
                    "executionTimeMilliseconds": 985,
                    "locale": "de",
                    "notifications": [],
                    "query": "fetch dt.system.events\n| filter event.kind == \"BILLING_USAGE_EVENT\" and event.type == \"Full-Stack Monitoring\"\n| dedup event.id\n| filter isNotNull(billed_gibibyte_hours)\n| filter billed_gibibyte_hours \u003e 0\n| makeTimeseries host_count = countDistinct(dt.entity.host), interval: 15m, time: usage.start",
                    "queryId": "8b1f8a3b-c1a0-4c26-b8b6-69f6a38e8b44",
                    "sampled": false,
                    "scannedBytes": 0,
                    "scannedDataPoints": 0,
                    "scannedRecords": 0,
                    "timezone": "Europe/Vienna"
                  }
                },
                "records": [
                  {
                    "host_count": [
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      21,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      22,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      21,
                      21,
                      21,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      20,
                      null
                    ],
                    "interval": "1800000000000",
                    "timeframe": {
                      "end": "2025-08-07T10:30:00.000000000+02:00",
                      "start": "2025-07-08T10:00:00.000000000+02:00"
                    }
                  }
                ],
                "types": [
                  {
                    "indexRange": [
                      0,
                      0
                    ],
                    "mappings": {
                      "host_count": {
                        "type": "array",
                        "types": [
                          {
                            "indexRange": [
                              0,
                              1440
                            ],
                            "mappings": {
                              "element": {
                                "type": "double"
                              }
                            }
                          }
                        ]
                      },
                      "interval": {
                        "type": "duration"
                      },
                      "timeframe": {
                        "type": "timeframe"
                      }
                    }
                  }
                ]
              }
            },
            "state": "success",
            "visualization": "lineChart",
            "visualizationSettings": {
              "autoSelectVisualization": false,
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "fieldMapping": {
                  "leftAxisValues": [
                    "host_count"
                  ],
                  "timestamp": "timeframe"
                },
                "gapPolicy": "connect",
                "hiddenLegendFields": [
                  "billed_gibibyte_hours"
                ],
                "leftYAxisSettings": {
                  "isLabelVisible": true,
                  "label": "Billed Hosts",
                  "min": "auto",
                  "scale": "linear"
                },
                "pointsDisplay": "never",
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisIsLabelVisible": false,
                "xAxisLabel": "timeframe",
                "xAxisScaling": "auto"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "categorical",
                "dataMappings": {},
                "displayedFields": [],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "total_hosts",
                "prefixIcon": "AnalyticsIcon",
                "recordField": "total_billed_hosts",
                "showLabel": true,
                "sparklineSettings": {
                  "record": "count()"
                },
                "trend": {
                  "isVisible": true,
                  "trendType": "auto"
                }
              },
              "table": {
                "columnTypeOverrides": [
                  {
                    "fields": [
                      "host_count"
                    ],
                    "id": 1744190217151,
                    "value": "sparkline"
                  }
                ],
                "columnWidths": {},
                "enableSparklines": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "title": "Overview - Number of billed hosts",
          "type": "dql"
        }
      ],
      "version": "7"
    })
  private = true
}
