resource "dynatrace_document" "Permission-Reviewer_RBAC" {
  name    = "Permission - Reviewer RBAC"
  type    = "notebook"
  content = jsonencode({
      "defaultSegments": [],
      "defaultTimeframe": {
        "from": "now()-2h",
        "to": "now()"
      },
      "sections": [
        {
          "id": "f64c8cd2-c921-444a-8b78-43a969f04bce",
          "markdown": "# RBAC Assessment\n\nPre-Reqs:\n- Generate an OAuth Client with following permissions:\n  - \"View users and groups\" = account-idm-read\n  - \"View and manage policies\" = iam-policies-management, iam:policies:write, iam:policies:read, iam:bindings:write, iam:bindings:read, iam:effective-permissions:read\n  - \"View environments\" = account-env-read, which allows reading ClientID and Secret from a credential\n\n\nUse the ClientId and ClientSecret you generated in the code below (authentication section)",
          "type": "markdown"
        },
        {
          "drilldownPath": [],
          "foldings": [],
          "height": 718,
          "id": "f6fdab68-cb58-47ea-a9ba-5ac5f57ab19c",
          "showTitle": false,
          "state": {
            "input": {
              "timeframe": {
                "from": "now()-2h",
                "to": "now()"
              },
              "value": "\nexport default async function () {\n\n  // Interfaces declarations\n  interface Token {\n      \"access_token\": string;\n      \"token_type\": string;\n      \"expires_in\": 3600;\n      \"scope\": string;\n      \"resource\" : string;\n  }\n  \n  interface Group {\n      uuid: string;\n      name: string;\n      description: string;\n      federatedAttributeValues: string[];\n      owner: string;\n      createdAt: string;\n      updatedAt: string;\n  }\n  \n  interface Permission {\n      \"access_token\": string;\n      \"token_type\": string;\n      \"expires_in\": 3600;\n      \"scope\": string;\n      \"resource\" : string;\n  }\n\n  const rbacToDefaultPolicyMapping = [\n    { rbacRole: \"tenant-viewer\", pbacRole: \"roles:viewer\", defPol: \"Standard User\" },\n    { rbacRole: \"tenant-view-security-problems\", pbacRole: \"roles:view-security-problems\", defPol: \"Standard User\" },\n    { rbacRole: \"tenant-manage-security-problems\", pbacRole: \"manage-security-problems\", defPol: \"Pro User\" },\n    { rbacRole: \"tenant-replay-sessions-with-masking\", pbacRole: \"roles:replay-sessions-with-masking\", defPol: \"Pro User\" },\n    { rbacRole: \"tenant-logviewer\", pbacRole: \"roles:logviewer\", defPol: \"Read Logs\" },\n    { rbacRole: \"tenant-agent-install\", pbacRole: \"roles:agent-install\", defPol: \"Admin User\" },\n    { rbacRole: \"tenant-manage-settings\", pbacRole: \"settings:objects:read; settings:objects:write; settings:schemas:read\", defPol: \"Admin User\" },\n    { rbacRole: \"tenant-configure-request-capture-data\", pbacRole: \"roles:configure-request-capture-data\", defPol: \"Admin User\" },\n    { rbacRole: \"tenant-manage-support-tickets\", pbacRole: \"none\", defPol: \"\" },\n    { rbacRole: \"tenant-replay-sessions-without-masking\", pbacRole: \"roles:replay-sessions-without-masking\", defPol: \"\"},\n    { rbacRole: \"tenant-view-sensitive-request-data\", pbacRole: \"roles:view-sensitive-request-data\", defPol: \"\" }\n];\n  \n  //Begin Authentication using OAuth\n\n  /*\n  //Option 1 (recommended): using credentials store\n  import { credentialVaultClient } from \"@dynatrace-sdk/client-classic-environment-v2\";\n  // PROVIDE credentialsId where you have stored your client_id and client_secret of your OAuth client\n  // please store the client_id in the username and the client_secret in the password of the credential\n  \n  const credentialsId = \"\u003cyour credentialsId goes here\u003e\";\n  const credentialDetails = await credentialVaultClient.getCredentialsDetails({ id: credentialsId });\n  const client_id = credentialDetails.username;\n  const client_secret = credentialDetails.password;\n  */\n  \n  //Option 2 (not recommended): hardcoding ClientId and Secret in the notebook code.\n  const client_id = \"<set_via_credentials_store>\";\n  const client_secret = \"<set_via_credentials_store>\";\n  //End Authentication using OAuth\n  \n  // Get the OAuth token for your account\n  const tokenResponse = await getOAuthToken(client_id,client_secret);\n  const token = tokenResponse.access_token;\n  const account = tokenResponse.resource.substring(14); \n\n  \n  var candidateRBACPermissions = new Array();\n  \n  const groups = await getGroups(account);\n  \n  for (const group of groups.filter(hasUsers))\n  {\n      const permissions = await getPermissions(group);\n      let environments = new Set\u003cstring\u003e();\n      for(const permission of permissions.filter(isTenantOrMgmtZoneScope)) {\n        if (permission.scopeType == \"management-zone\") {\n          permission[\"mgmtzone_name\"] = await getMgmtZone_Name(permission.scope.split(\":\")[1])\n        }\n        permission[\"group_uuid\"] = group.uuid;\n        permission[\"group_name\"] = group.name;\n        permission[\"group_description\"] = group.description;\n        permission[\"group_owner\"] = group.owner;\n        let lookup = rbacToDefaultPolicyMapping.find(o =\u003e o.rbacRole === permission.permissionName);\n        if (typeof lookup !== 'undefined') {\n          permission[\"pbacRole\"] = lookup.pbacRole;\n          permission[\"recommended_default_policy\"] = lookup.defPol;\n        }\n        candidateRBACPermissions.push(permission);\n      }\n  }\n\n  async function getOAuthToken (client_id:string,client_secret:string):Promise\u003cToken\u003e {\n    const oauth_url = \"https://sso.dynatrace.com/sso/oauth2/token\";\n    const body = {\"grant_type\":\"client_credentials\", \"client_id\":client_id, \"client_secret\": client_secret}\n    const params = new URLSearchParams();\n    \n    params.append(\"grant_type\", \"client_credentials\");\n    params.append(\"client_id\", client_id);\n    params.append(\"client_secret\", client_secret);\n      \n    const response = await fetch(oauth_url,\n    {\n            method: 'POST',\n            headers: {\n                'Content-Type': \"application/x-www-form-urlencoded\"\n            },\n            body: params\n    });\n    const data = await response.json();\n    return data;\n  }\n\n  async function getGroups(account: string):Promise\u003cGroup[]\u003e {\n    const group_url = `https://api.dynatrace.com/iam/v1/accounts/$${account}/groups`;\n\n    const response = await fetch(group_url,\n    {\n            method: 'GET',\n            headers: {\n                'Authorization': \"Bearer \" + token\n            },\n    })\n    const data = await response.json();\n    return data.items;\n  }\n\n  function isTenantOrMgmtZoneScope(permission:Permission):boolean {\n    return permission.scopeType == \"tenant\" || permission.scopeType == \"management-zone\";\n  }\n\n  async function hasUsers(group:Group):boolean {\n    const group_users_url = `https://api.dynatrace.com/iam/v1/accounts/$${account}/groups/$${group.uuid}/users`;\n\n    const response = await fetch(group_users_url,\n    {\n            method: 'GET',\n            headers: {\n                'Authorization': \"Bearer \" + token\n            },\n    })\n    const data = await response.json();\n    return Object.keys(data).length \u003e 0;\n  }\n\n  async function getPermissions(group: Group):Promise\u003cPermission[]\u003e {\n    const perm_url = `https://api.dynatrace.com/iam/v1/accounts/$${account}/groups/$${group.uuid}/permissions`;\n    const response = await fetch(perm_url,\n    {\n    \t\tmethod: 'GET',\n    \t\theaders: {\n    \t\t\t'Authorization': \"Bearer \" + token\n    \t\t},\n    })\n    const data = await response.json();\n    return data.permissions;\n  }\n\n  async function getMgmtZone_Name(zoneId: String):String {\n\n    const env_url = `https://api.dynatrace.com/env/v1/accounts/$${account}/environments`;\n  \n    const response = await fetch(env_url,\n    {\n    \t\tmethod: 'GET',\n    \t\theaders: {\n    \t\t\t'Authorization': \"Bearer \" + token\n    \t\t},\n    })\n    const data = await response.json();\n    \n    let newArray = data.managementZoneResources.filter(function (el) {\n        return el.id == zoneId;\n      }\n    );\n\n    let mgmtZoneName = \"Not found\"\n    if (newArray.length == 1) {\n      mgmtZoneName = newArray[0].name\n    }\n    return mgmtZoneName;\n\n  }\n\n  return candidateRBACPermissions;\n}\n\n"
            },
            "querySettings": {
              "defaultSamplingRatio": 10,
              "defaultScanLimitGbytes": 500,
              "enableSampling": false,
              "maxResultMegaBytes": 1,
              "maxResultRecords": 1000
            },
            "result": {
              "code": 200,
              "dateTime": "2025-07-09T09:52:43.127Z",
              "input": {
                "timeframe": {
                  "from": "now()-2h",
                  "to": "now()"
                },
                "value": "\nexport default async function () {\n\n  // Interfaces declarations\n  interface Token {\n      \"access_token\": string;\n      \"token_type\": string;\n      \"expires_in\": 3600;\n      \"scope\": string;\n      \"resource\" : string;\n  }\n  \n  interface Group {\n      uuid: string;\n      name: string;\n      description: string;\n      federatedAttributeValues: string[];\n      owner: string;\n      createdAt: string;\n      updatedAt: string;\n  }\n  \n  interface Permission {\n      \"access_token\": string;\n      \"token_type\": string;\n      \"expires_in\": 3600;\n      \"scope\": string;\n      \"resource\" : string;\n  }\n\n  const rbacToDefaultPolicyMapping = [\n    { rbacRole: \"tenant-viewer\", pbacRole: \"roles:viewer\", defPol: \"Standard User\" },\n    { rbacRole: \"tenant-view-security-problems\", pbacRole: \"roles:view-security-problems\", defPol: \"Standard User\" },\n    { rbacRole: \"tenant-manage-security-problems\", pbacRole: \"manage-security-problems\", defPol: \"Pro User\" },\n    { rbacRole: \"tenant-replay-sessions-with-masking\", pbacRole: \"roles:replay-sessions-with-masking\", defPol: \"Pro User\" },\n    { rbacRole: \"tenant-logviewer\", pbacRole: \"roles:logviewer\", defPol: \"Read Logs\" },\n    { rbacRole: \"tenant-agent-install\", pbacRole: \"roles:agent-install\", defPol: \"Admin User\" },\n    { rbacRole: \"tenant-manage-settings\", pbacRole: \"settings:objects:read; settings:objects:write; settings:schemas:read\", defPol: \"Admin User\" },\n    { rbacRole: \"tenant-configure-request-capture-data\", pbacRole: \"roles:configure-request-capture-data\", defPol: \"Admin User\" },\n    { rbacRole: \"tenant-manage-support-tickets\", pbacRole: \"none\", defPol: \"\" },\n    { rbacRole: \"tenant-replay-sessions-without-masking\", pbacRole: \"roles:replay-sessions-without-masking\", defPol: \"\"},\n    { rbacRole: \"tenant-view-sensitive-request-data\", pbacRole: \"roles:view-sensitive-request-data\", defPol: \"\" }\n];\n  \n  //Begin Authentication using OAuth\n\n  /*\n  //Option 1 (recommended): using credentials store\n  import { credentialVaultClient } from \"@dynatrace-sdk/client-classic-environment-v2\";\n  // PROVIDE credentialsId where you have stored your client_id and client_secret of your OAuth client\n  // please store the client_id in the username and the client_secret in the password of the credential\n  \n  const credentialsId = \"\u003cyour credentialsId goes here\u003e\";\n  const credentialDetails = await credentialVaultClient.getCredentialsDetails({ id: credentialsId });\n  const client_id = credentialDetails.username;\n  const client_secret = credentialDetails.password;\n  */\n  \n  //Option 2 (not recommended): hardcoding ClientId and Secret in the notebook code.\n  const client_id = \"<set_via_credentials_store>\";\n  const client_secret = \"<set_via_credentials_store>\";\n  //End Authentication using OAuth\n  \n  // Get the OAuth token for your account\n  const tokenResponse = await getOAuthToken(client_id,client_secret);\n  const token = tokenResponse.access_token;\n  const account = tokenResponse.resource.substring(14); \n\n  \n  var candidateRBACPermissions = new Array();\n  \n  const groups = await getGroups(account);\n  \n  for (const group of groups.filter(hasUsers))\n  {\n      const permissions = await getPermissions(group);\n      let environments = new Set\u003cstring\u003e();\n      for(const permission of permissions.filter(isTenantOrMgmtZoneScope)) {\n        if (permission.scopeType == \"management-zone\") {\n          permission[\"mgmtzone_name\"] = await getMgmtZone_Name(permission.scope.split(\":\")[1])\n        }\n        permission[\"group_uuid\"] = group.uuid;\n        permission[\"group_name\"] = group.name;\n        permission[\"group_description\"] = group.description;\n        permission[\"group_owner\"] = group.owner;\n        let lookup = rbacToDefaultPolicyMapping.find(o =\u003e o.rbacRole === permission.permissionName);\n        if (typeof lookup !== 'undefined') {\n          permission[\"pbacRole\"] = lookup.pbacRole;\n          permission[\"recommended_default_policy\"] = lookup.defPol;\n        }\n        candidateRBACPermissions.push(permission);\n      }\n  }\n\n  async function getOAuthToken (client_id:string,client_secret:string):Promise\u003cToken\u003e {\n    const oauth_url = \"https://sso.dynatrace.com/sso/oauth2/token\";\n    const body = {\"grant_type\":\"client_credentials\", \"client_id\":client_id, \"client_secret\": client_secret}\n    const params = new URLSearchParams();\n    \n    params.append(\"grant_type\", \"client_credentials\");\n    params.append(\"client_id\", client_id);\n    params.append(\"client_secret\", client_secret);\n      \n    const response = await fetch(oauth_url,\n    {\n            method: 'POST',\n            headers: {\n                'Content-Type': \"application/x-www-form-urlencoded\"\n            },\n            body: params\n    });\n    const data = await response.json();\n    return data;\n  }\n\n  async function getGroups(account: string):Promise\u003cGroup[]\u003e {\n    const group_url = `https://api.dynatrace.com/iam/v1/accounts/$${account}/groups`;\n\n    const response = await fetch(group_url,\n    {\n            method: 'GET',\n            headers: {\n                'Authorization': \"Bearer \" + token\n            },\n    })\n    const data = await response.json();\n    return data.items;\n  }\n\n  function isTenantOrMgmtZoneScope(permission:Permission):boolean {\n    return permission.scopeType == \"tenant\" || permission.scopeType == \"management-zone\";\n  }\n\n  async function hasUsers(group:Group):boolean {\n    const group_users_url = `https://api.dynatrace.com/iam/v1/accounts/$${account}/groups/$${group.uuid}/users`;\n\n    const response = await fetch(group_users_url,\n    {\n            method: 'GET',\n            headers: {\n                'Authorization': \"Bearer \" + token\n            },\n    })\n    const data = await response.json();\n    return Object.keys(data).length \u003e 0;\n  }\n\n  async function getPermissions(group: Group):Promise\u003cPermission[]\u003e {\n    const perm_url = `https://api.dynatrace.com/iam/v1/accounts/$${account}/groups/$${group.uuid}/permissions`;\n    const response = await fetch(perm_url,\n    {\n    \t\tmethod: 'GET',\n    \t\theaders: {\n    \t\t\t'Authorization': \"Bearer \" + token\n    \t\t},\n    })\n    const data = await response.json();\n    return data.permissions;\n  }\n\n  async function getMgmtZone_Name(zoneId: String):String {\n\n    const env_url = `https://api.dynatrace.com/env/v1/accounts/$${account}/environments`;\n  \n    const response = await fetch(env_url,\n    {\n    \t\tmethod: 'GET',\n    \t\theaders: {\n    \t\t\t'Authorization': \"Bearer \" + token\n    \t\t},\n    })\n    const data = await response.json();\n    \n    let newArray = data.managementZoneResources.filter(function (el) {\n        return el.id == zoneId;\n      }\n    );\n\n    let mgmtZoneName = \"Not found\"\n    if (newArray.length == 1) {\n      mgmtZoneName = newArray[0].name\n    }\n    return mgmtZoneName;\n\n  }\n\n  return candidateRBACPermissions;\n}\n\n"
              },
              "logs": "",
              "notifications": [],
              "value": [
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can view personal data (for example, method arguments) and configure request-data capture rules",
                  "group_name": "XXX Confidential data admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "7104353c-64df-4da2-9238-2f35898ca151",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can view personal data (for example, method arguments) and configure request-data capture rules",
                  "group_name": "XXX Confidential data admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "7104353c-64df-4da2-9238-2f35898ca151",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can view personal data (for example, method arguments) and configure request-data capture rules",
                  "group_name": "XXX Confidential data admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "7104353c-64df-4da2-9238-2f35898ca151",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can view personal data (for example, method arguments) and configure request-data capture rules",
                  "group_name": "XXX Confidential data admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "7104353c-64df-4da2-9238-2f35898ca151",
                  "pbacRole": "roles:configure-request-capture-data",
                  "permissionName": "tenant-configure-request-capture-data",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can view personal data (for example, method arguments) and configure request-data capture rules",
                  "group_name": "XXX Confidential data admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "7104353c-64df-4da2-9238-2f35898ca151",
                  "pbacRole": "roles:view-sensitive-request-data",
                  "permissionName": "tenant-view-sensitive-request-data",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can view and configure security-related issues and settings",
                  "group_name": "XXX Security admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "71acc3cc-95df-4195-9580-18348ae9700f",
                  "pbacRole": "manage-security-problems",
                  "permissionName": "tenant-manage-security-problems",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can access and view the contents of log files, but has no other access rights. Reserved for users who need access to sensitive log file data",
                  "group_name": "XXX Log viewer",
                  "group_owner": "LOCAL",
                  "group_uuid": "906752b1-3980-4dfa-84fd-a4c8757c9291",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can access and view the contents of log files, but has no other access rights. Reserved for users who need access to sensitive log file data",
                  "group_name": "XXX Log viewer",
                  "group_owner": "LOCAL",
                  "group_uuid": "906752b1-3980-4dfa-84fd-a4c8757c9291",
                  "pbacRole": "roles:logviewer",
                  "permissionName": "tenant-logviewer",
                  "recommended_default_policy": "Read Logs",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can access and view the contents of log files, but has no other access rights. Reserved for users who need access to sensitive log file data",
                  "group_name": "XXX Log viewer",
                  "group_owner": "LOCAL",
                  "group_uuid": "906752b1-3980-4dfa-84fd-a4c8757c9291",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "Has read-only access to the environment and can download/install OneAgent, but cannot change environment settings",
                  "group_name": "XXX Deployment admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "518d6b19-8271-4e47-802e-ba04c4e734d3",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "Has read-only access to the environment and can download/install OneAgent, but cannot change environment settings",
                  "group_name": "XXX Deployment admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "518d6b19-8271-4e47-802e-ba04c4e734d3",
                  "pbacRole": "roles:agent-install",
                  "permissionName": "tenant-agent-install",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "Has read-only access to the environment and can download/install OneAgent, but cannot change environment settings",
                  "group_name": "XXX Deployment admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "518d6b19-8271-4e47-802e-ba04c4e734d3",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "has full environment access. Can change monitoring settings, and download/install OneAgent",
                  "group_name": "XXX Monitoring admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "4a2126e7-dc7b-447a-a39d-bd21fed096cc",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "has full environment access. Can change monitoring settings, and download/install OneAgent",
                  "group_name": "XXX Monitoring admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "4a2126e7-dc7b-447a-a39d-bd21fed096cc",
                  "pbacRole": "none",
                  "permissionName": "tenant-manage-support-tickets",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "has full environment access. Can change monitoring settings, and download/install OneAgent",
                  "group_name": "XXX Monitoring admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "4a2126e7-dc7b-447a-a39d-bd21fed096cc",
                  "pbacRole": "roles:agent-install",
                  "permissionName": "tenant-agent-install",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "has full environment access. Can change monitoring settings, and download/install OneAgent",
                  "group_name": "XXX Monitoring admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "4a2126e7-dc7b-447a-a39d-bd21fed096cc",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "has full environment access. Can change monitoring settings, and download/install OneAgent",
                  "group_name": "XXX Monitoring admin",
                  "group_owner": "LOCAL",
                  "group_uuid": "4a2126e7-dc7b-447a-a39d-bd21fed096cc",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can access the environment in read-only mode, but cannot download/install OneAgent or change environment settings",
                  "group_name": "XXX Monitoring viewer",
                  "group_owner": "LOCAL",
                  "group_uuid": "485e97dd-bbdc-43b9-9efb-7f9647928957",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2022-11-10T14:22:14Z",
                  "group_description": "can access the environment in read-only mode, but cannot download/install OneAgent or change environment settings",
                  "group_name": "XXX Monitoring viewer",
                  "group_owner": "LOCAL",
                  "group_uuid": "485e97dd-bbdc-43b9-9efb-7f9647928957",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2022-11-10T14:22:14Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:view-sensitive-request-data",
                  "permissionName": "tenant-view-sensitive-request-data",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "none",
                  "permissionName": "tenant-manage-support-tickets",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "manage-security-problems",
                  "permissionName": "tenant-manage-security-problems",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:configure-request-capture-data",
                  "permissionName": "tenant-configure-request-capture-data",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:view-security-problems",
                  "permissionName": "tenant-view-security-problems",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:replay-sessions-without-masking",
                  "permissionName": "tenant-replay-sessions-without-masking",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-07-22T13:44:40Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:agent-install",
                  "permissionName": "tenant-agent-install",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-22T13:44:40Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "manage-security-problems",
                  "permissionName": "tenant-manage-security-problems",
                  "recommended_default_policy": "Pro User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "none",
                  "permissionName": "tenant-manage-support-tickets",
                  "recommended_default_policy": "",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:view-sensitive-request-data",
                  "permissionName": "tenant-view-sensitive-request-data",
                  "recommended_default_policy": "",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:configure-request-capture-data",
                  "permissionName": "tenant-configure-request-capture-data",
                  "recommended_default_policy": "Admin User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:agent-install",
                  "permissionName": "tenant-agent-install",
                  "recommended_default_policy": "Admin User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2024-08-06T09:26:56Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:view-security-problems",
                  "permissionName": "tenant-view-security-problems",
                  "recommended_default_policy": "Standard User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2024-08-06T09:26:56Z"
                },
                {
                  "createdAt": "2025-04-09T07:58:28Z",
                  "group_description": null,
                  "group_name": "2217_Dynatrace_Admins",
                  "group_owner": "SCIM",
                  "group_uuid": "2df7348e-1fef-4da6-aec5-dae53b81cc42",
                  "pbacRole": "roles:replay-sessions-without-masking",
                  "permissionName": "tenant-replay-sessions-without-masking",
                  "recommended_default_policy": "",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2025-04-09T07:58:28Z"
                },
                {
                  "createdAt": "2024-10-29T08:51:06Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:51:06Z"
                },
                {
                  "createdAt": "2024-10-29T08:52:12Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:52:12Z"
                },
                {
                  "createdAt": "2024-10-29T08:53:13Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "roles:view-sensitive-request-data",
                  "permissionName": "tenant-view-sensitive-request-data",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:53:13Z"
                },
                {
                  "createdAt": "2024-10-29T08:54:02Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:54:02Z"
                },
                {
                  "createdAt": "2024-10-29T08:56:48Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "roles:logviewer",
                  "permissionName": "tenant-logviewer",
                  "recommended_default_policy": "Read Logs",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:56:48Z"
                },
                {
                  "createdAt": "2024-10-29T08:57:09Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "roles:configure-request-capture-data",
                  "permissionName": "tenant-configure-request-capture-data",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:57:09Z"
                },
                {
                  "createdAt": "2024-10-29T08:58:07Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "roles:agent-install",
                  "permissionName": "tenant-agent-install",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:58:07Z"
                },
                {
                  "createdAt": "2024-10-29T08:58:24Z",
                  "group_description": null,
                  "group_name": "2217_dt_sap_tpi",
                  "group_owner": "SCIM",
                  "group_uuid": "df6d3245-f3f9-4bca-b218-7f60600665a5",
                  "pbacRole": "none",
                  "permissionName": "tenant-manage-support-tickets",
                  "recommended_default_policy": "",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-10-29T08:58:24Z"
                },
                {
                  "createdAt": "2024-07-31T08:47:54Z",
                  "group_description": null,
                  "group_name": "2217_dt_xecm_steel_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "1497f4c9-7f23-4dd0-9f0e-f5deff104b90",
                  "mgmtzone_name": "xECM - Enterprise Content Management",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769:165550499436117936",
                  "scopeType": "management-zone",
                  "updatedAt": "2024-07-31T08:47:54Z"
                },
                {
                  "createdAt": "2024-07-31T08:47:54Z",
                  "group_description": null,
                  "group_name": "2217_dt_xecm_steel_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "1497f4c9-7f23-4dd0-9f0e-f5deff104b90",
                  "mgmtzone_name": "xECM - Enterprise Content Management",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769:165550499436117936",
                  "scopeType": "management-zone",
                  "updatedAt": "2024-07-31T08:47:54Z"
                },
                {
                  "createdAt": "2024-07-31T11:20:44Z",
                  "group_description": null,
                  "group_name": "2217_dt_xecm_steel_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "1497f4c9-7f23-4dd0-9f0e-f5deff104b90",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-31T11:20:44Z"
                },
                {
                  "createdAt": "2024-07-31T11:25:05Z",
                  "group_description": null,
                  "group_name": "2217_dt_xecm_steel_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "1497f4c9-7f23-4dd0-9f0e-f5deff104b90",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2024-07-31T11:25:05Z"
                },
                {
                  "createdAt": "2025-07-09T06:54:28Z",
                  "group_description": null,
                  "group_name": "2217_dt_xecm_steel_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "1497f4c9-7f23-4dd0-9f0e-f5deff104b90",
                  "mgmtzone_name": "xECM - Enterprise Content Management",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769:165550499436117936",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-07-09T06:54:28Z"
                },
                {
                  "createdAt": "2025-07-09T06:54:28Z",
                  "group_description": null,
                  "group_name": "2217_dt_xecm_steel_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "1497f4c9-7f23-4dd0-9f0e-f5deff104b90",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2025-07-09T06:54:28Z"
                },
                {
                  "createdAt": "2025-04-09T07:45:56Z",
                  "group_description": null,
                  "group_name": "2217_dt_itsm_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "3b29fae5-fdfa-42f1-b104-4cf7d980446d",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2025-04-09T07:45:56Z"
                },
                {
                  "createdAt": "2025-04-09T07:45:56Z",
                  "group_description": null,
                  "group_name": "2217_dt_itsm_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "3b29fae5-fdfa-42f1-b104-4cf7d980446d",
                  "mgmtzone_name": "ITSM - BMC Remedy",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769:6156115154806518891",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-04-09T07:45:56Z"
                },
                {
                  "createdAt": "2025-03-12T11:56:39Z",
                  "group_description": null,
                  "group_name": "2217_dt_bee4it_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "a6288044-480d-474f-8052-8e8507c83b3a",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2025-03-12T11:56:39Z"
                },
                {
                  "createdAt": "2025-03-12T11:56:39Z",
                  "group_description": null,
                  "group_name": "2217_dt_bee4it_admin",
                  "group_owner": "SCIM",
                  "group_uuid": "a6288044-480d-474f-8052-8e8507c83b3a",
                  "mgmtzone_name": "Bee4IT",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769:803242235667889460",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-03-12T11:56:39Z"
                },
                {
                  "createdAt": "2025-01-21T13:50:49Z",
                  "group_description": null,
                  "group_name": "2217_dt_itportal_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "18e486bf-7a9d-4ae2-8667-736cb08f1f4b",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2025-01-21T13:50:49Z"
                },
                {
                  "createdAt": "2025-01-21T13:50:49Z",
                  "group_description": null,
                  "group_name": "2217_dt_itportal_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "18e486bf-7a9d-4ae2-8667-736cb08f1f4b",
                  "mgmtzone_name": "IT Portal",
                  "pbacRole": "settings:objects:read; settings:objects:write; settings:schemas:read",
                  "permissionName": "tenant-manage-settings",
                  "recommended_default_policy": "Admin User",
                  "scope": "hgm72482:3195634098735953146",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-01-21T13:50:49Z"
                },
                {
                  "createdAt": "2025-01-21T13:51:20Z",
                  "group_description": null,
                  "group_name": "2217_dt_itportal_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "18e486bf-7a9d-4ae2-8667-736cb08f1f4b",
                  "mgmtzone_name": "IT Portal",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "hgm72482:3195634098735953146",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-01-21T13:51:20Z"
                },
                {
                  "createdAt": "2025-01-21T13:51:20Z",
                  "group_description": null,
                  "group_name": "2217_dt_itportal_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "18e486bf-7a9d-4ae2-8667-736cb08f1f4b",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2025-01-21T13:51:20Z"
                },
                {
                  "createdAt": "2025-01-21T13:51:48Z",
                  "group_description": null,
                  "group_name": "2217_dt_itportal_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "18e486bf-7a9d-4ae2-8667-736cb08f1f4b",
                  "mgmtzone_name": "IT Portal",
                  "pbacRole": "roles:replay-sessions-without-masking",
                  "permissionName": "tenant-replay-sessions-without-masking",
                  "recommended_default_policy": "",
                  "scope": "hgm72482:3195634098735953146",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-01-21T13:51:48Z"
                },
                {
                  "createdAt": "2025-01-21T13:51:48Z",
                  "group_description": null,
                  "group_name": "2217_dt_itportal_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "18e486bf-7a9d-4ae2-8667-736cb08f1f4b",
                  "pbacRole": "roles:replay-sessions-without-masking",
                  "permissionName": "tenant-replay-sessions-without-masking",
                  "recommended_default_policy": "",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2025-01-21T13:51:48Z"
                },
                {
                  "createdAt": "2025-04-09T07:17:29Z",
                  "group_description": null,
                  "group_name": "2217_dt_pam_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "1937f341-adfe-4ac8-b861-dc520e9ff2c9",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2025-04-09T07:17:29Z"
                },
                {
                  "createdAt": "2025-04-09T07:17:29Z",
                  "group_description": null,
                  "group_name": "2217_dt_pam_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "1937f341-adfe-4ac8-b861-dc520e9ff2c9",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2025-04-09T07:17:29Z"
                },
                {
                  "createdAt": "2025-04-09T07:17:29Z",
                  "group_description": null,
                  "group_name": "2217_dt_pam_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "1937f341-adfe-4ac8-b861-dc520e9ff2c9",
                  "mgmtzone_name": "PAM - Privileged Access Management",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "hgm72482:-955075196887745216",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-04-09T07:17:29Z"
                },
                {
                  "createdAt": "2025-04-09T07:17:29Z",
                  "group_description": null,
                  "group_name": "2217_dt_pam_owner",
                  "group_owner": "SCIM",
                  "group_uuid": "1937f341-adfe-4ac8-b861-dc520e9ff2c9",
                  "mgmtzone_name": "PAM - Privileged Access Management",
                  "pbacRole": "roles:replay-sessions-with-masking",
                  "permissionName": "tenant-replay-sessions-with-masking",
                  "recommended_default_policy": "Pro User",
                  "scope": "uqy31769:4669812108757315874",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-04-09T07:17:29Z"
                },
                {
                  "createdAt": "2025-04-28T08:30:59Z",
                  "group_description": null,
                  "group_name": "temp_dt_sap_businessclient",
                  "group_owner": "LOCAL",
                  "group_uuid": "7bb151d0-63ba-4f08-bc74-6b3847ffdb62",
                  "mgmtzone_name": "SAP BusinessClient",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "hgm72482:1294361406141970392",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-04-28T08:30:59Z"
                },
                {
                  "createdAt": "2025-04-28T08:30:59Z",
                  "group_description": null,
                  "group_name": "temp_dt_sap_businessclient",
                  "group_owner": "LOCAL",
                  "group_uuid": "7bb151d0-63ba-4f08-bc74-6b3847ffdb62",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "hgm72482",
                  "scopeType": "tenant",
                  "updatedAt": "2025-04-28T08:30:59Z"
                },
                {
                  "createdAt": "2025-05-19T09:34:46Z",
                  "group_description": null,
                  "group_name": "temp_dt_sap_businessclient",
                  "group_owner": "LOCAL",
                  "group_uuid": "7bb151d0-63ba-4f08-bc74-6b3847ffdb62",
                  "mgmtzone_name": "POC (SAP) - TPI UI5 VQG",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769:-5751466047146216353",
                  "scopeType": "management-zone",
                  "updatedAt": "2025-05-19T09:34:46Z"
                },
                {
                  "createdAt": "2025-05-19T09:34:46Z",
                  "group_description": null,
                  "group_name": "temp_dt_sap_businessclient",
                  "group_owner": "LOCAL",
                  "group_uuid": "7bb151d0-63ba-4f08-bc74-6b3847ffdb62",
                  "pbacRole": "roles:viewer",
                  "permissionName": "tenant-viewer",
                  "recommended_default_policy": "Standard User",
                  "scope": "uqy31769",
                  "scopeType": "tenant",
                  "updatedAt": "2025-05-19T09:34:46Z"
                }
              ]
            },
            "state": "success",
            "visualization": "table",
            "visualizationSettings": {
              "chartSettings": {
                "categoricalBarChartSettings": {
                  "categoryAxisLabel": "permissionName",
                  "categoryAxisTickLayout": "horizontal",
                  "colorPaletteMode": "multi-color",
                  "groupMode": "stacked",
                  "layout": "horizontal",
                  "scale": "absolute",
                  "tooltipVariant": "single",
                  "valueAxisLabel": "",
                  "valueAxisScale": "linear"
                },
                "categoryOverrides": {},
                "circleChartSettings": {
                  "groupingThresholdType": "relative",
                  "groupingThresholdValue": 0,
                  "valueType": "relative"
                },
                "colorPalette": "categorical",
                "curve": "linear",
                "gapPolicy": "connect",
                "pointsDisplay": "auto",
                "truncationMode": "middle",
                "valueRepresentation": "absolute",
                "xAxisScaling": "analyzedTimeframe"
              },
              "histogram": {
                "colorPalette": "categorical",
                "dataMappings": [],
                "legend": {
                  "position": "auto"
                },
                "truncationMode": "middle",
                "variant": "single",
                "yAxis": {
                  "isLabelVisible": true,
                  "label": "Frequency",
                  "scale": "linear"
                }
              },
              "honeycomb": {
                "colorMode": "color-palette",
                "colorPalette": "categorical",
                "dataMappings": {},
                "displayedFields": [],
                "labels": {
                  "showLabels": false
                },
                "legend": {
                  "hidden": false,
                  "position": "auto",
                  "ratio": "auto"
                },
                "shape": "hexagon",
                "truncationMode": "middle"
              },
              "singleValue": {
                "alignment": "center",
                "autoscale": true,
                "colorThresholdTarget": "value",
                "isIconVisible": false,
                "label": "",
                "prefixIcon": "",
                "recordField": "error",
                "showLabel": true
              },
              "table": {
                "columnOrder": [
                  "[\"permissionName\"]",
                  "[\"scope\"]",
                  "[\"scopeType\"]",
                  "[\"createdAt\"]",
                  "[\"updatedAt\"]",
                  "[\"group_uuid\"]",
                  "[\"group_name\"]",
                  "[\"group_description\"]",
                  "[\"group_owner\"]",
                  "[\"pbacRole\"]",
                  "[\"recommended_default_policy\"]",
                  "[\"mgmtzone_name\"]"
                ],
                "columnTypeOverrides": [],
                "columnWidths": {
                  "[\"group_name\"]": 471.23,
                  "[\"permissionName\"]": 290.7375183105469,
                  "[\"scope\"]": 323.0500030517578,
                  "[\"scopeType\"]": 153.08750915527344
                },
                "enableSparklines": false,
                "firstVisibleRowIndex": 0,
                "hiddenColumns": [
                  [
                    "createdAt"
                  ],
                  [
                    "updatedAt"
                  ],
                  [
                    "group_uuid"
                  ],
                  [
                    "group_description"
                  ],
                  [
                    "group_owner"
                  ]
                ],
                "lineWrapIds": [],
                "linewrapEnabled": false,
                "monospacedFontColumns": [],
                "monospacedFontEnabled": false,
                "rowDensity": "condensed"
              },
              "thresholds": [],
              "valueBoundaries": {
                "max": "auto",
                "min": "auto"
              }
            }
          },
          "type": "function"
        }
      ],
      "version": "7"
    })
  private = true
}

