resource "dynatrace_document" "Send_open_issues_to_Slack" {
  name      = "Send open issues to Slack"
  type      = "workflow-template"
  content   =<<-EOT
    metadata:
      version: '1'
      trackingId: open-gitlab-issues
      dependencies:
        apps:
        - id: dynatrace.automations
          version: ^1.2632.0
        - id: dynatrace.gitlab.connector
          version: ^2.1.5
        - id: dynatrace.slack
          version: ^3.2.3
      inputs:
      - type: connection
        schema: app:dynatrace.gitlab.connector:connection
        targets:
        - tasks.list_issues.connection
      - type: connection
        schema: app:dynatrace.slack:connection
        targets:
        - tasks.send_message.connection
    workflow:
      title: Send open issues to Slack
      description: Gathers open issues from GitLab, process them, and forwards them to Slack
      schemaVersion: 3
      trigger: {}
      result: null
      type: STANDARD
      input: {}
      hourlyExecutionLimit: 1000
      guide: |
        # Setup
    
        This workflow requires connections to both GitLab and Slack.
    
        **GitLab connection**: If your environment doesn't already have a GitLab connection, you'll need to create one. For detailed instructions, see [Set up GitLab integration](https://docs.dynatrace.com/docs/analyze-explore-automate/workflows/actions/gitlab).
    
        **Slack connection**: If your environment doesn't already have a Slack connection, you'll need to create one. For detailed instructions, see [Set up Slack integration](https://docs.dynatrace.com/docs/analyze-explore-automate/workflows/actions/slack).
    
        # Trigger
    
        By default, this workflow uses an on-demand [trigger](?trigger=).
    
        You can leave it as-is to trigger the workflow manually or via API. You can update the trigger to run on a schedule (for example, daily or weekly at a specific time).
    
        # Retrieve issues
    
        In the task [list_issues](?task=list_issues&tab=input), you must specify the **projectId** from which to retrieve GitLab issues.
    
        You can also customize the filtering:
        - **issue_type**: Set to `issue` by default. Change to retrieve other types.
        - **labels**: Filter issues by specific labels.
        - **title**: Search for issues by title keywords.
        - **iid**: Retrieve a specific issue by its internal ID.
    
        Note: This task returns a maximum of 30 issues.
    
        # Configure the message
    
        In the task [send_message](?task=send_message&tab=input), you must specify the **channel** where the Slack message will be sent to.
    
        The message content is generated by the [create_message](?task=create_message&tab=input) task, which formats the issues as a bulleted list with links. You can modify the JavaScript code in this task to customize the message format or include additional issue information.
    
        # Customization examples
    
        **Filter by label**: To retrieve only issues with specific labels, add the label names in the [list_issues](?task=list_issues&tab=input) task's **labels** field (comma-separated).
    
        **Customize message format**: Edit the JavaScript code in [create_message](?task=create_message&tab=input) to change how issues are displayed. For example, you can include issue assignees, creation dates, or status information from the `issue` object.
    
      tasks:
        list_issues:
          name: list_issues
          input:
            iid: ''
            title: ''
            labels: ''
            projectId: ''
            connection: ''
            issue_type: issue
          action: dynatrace.gitlab.connector:gitlab-issue-list
          position:
            x: 0
            y: 1
          description: Search and list existing issues in GitLab (returns 30 issues max.)
          predecessors: []
        send_message:
          name: send_message
          input:
            channel: ''
            message: 'Open Issues:
    
              {{result("create_message")["message"]}}
    
    
              <{{execution().link}}|Workflow execution>'
            reaction: []
            connection: ''
            channelType: id
            executionDate: '{{ execution().started_at }}'
            appendToThread: false
            replyBroadcast: false
            selectedRequestType: 0
            attachmentToggleValue: none
          action: dynatrace.slack:slack-send-message
          position:
            x: 0
            y: 3
          conditions:
            states:
              create_message: OK
          description: Send a message to a Slack workspace
          predecessors:
          - create_message
        create_message:
          name: create_message
          input:
            script: "import { result } from '@dynatrace-sdk/automation-utils';\n\nexport\
              \ default async function () {\n  const { issues } = await result('list_issues');\n\
              \  let message = \"\";\n  for (const issue of issues) {\n    message +=\
              \ `• <$${issue.web_url}|$${issue.title}> \\n`; \n  }\n  return { message };\n\
              }"
          action: dynatrace.automations:run-javascript
          position:
            x: 0
            y: 2
          conditions:
            states:
              list_issues: OK
          description: Run custom JavaScript code.
          predecessors:
          - list_issues
    EOT
  custom_id = "dynatrace.gitlab.connector.send-open-issues-to-slack"
  # private = false
}
