resource "dynatrace_document" "Smartscape_Troubleshooting" {
  name    = "Smartscape Troubleshooting"
  type    = "dashboard"
  content = jsonencode({
      "annotations": [],
      "importedWithCode": false,
      "layouts": {
        "1": {
          "h": 16,
          "w": 24,
          "x": 0,
          "y": 0
        },
        "2": {
          "h": 14,
          "w": 24,
          "x": 0,
          "y": 16
        },
        "3": {
          "h": 4,
          "w": 24,
          "x": 0,
          "y": 30
        },
        "4": {
          "h": 7,
          "w": 7,
          "x": 0,
          "y": 34
        },
        "5": {
          "h": 7,
          "w": 17,
          "x": 7,
          "y": 34
        },
        "6": {
          "h": 5,
          "w": 22,
          "x": 0,
          "y": 41
        },
        "7": {
          "h": 6,
          "w": 22,
          "x": 0,
          "y": 46
        }
      },
      "settings": {},
      "tiles": {
        "1": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "smartscapeNodes \"*\"\n| fields id,name, type,dt.security_context\n| filter matchesValue(dt.security_context,\"network\")",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "title": "",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true,
            "table": {
              "columnWidths": {
                "[\"dt.security_context\"]": 169.59,
                "[\"type\"]": 225
              },
              "sortBy": [
                {
                  "columnId": "[\"name\"]",
                  "direction": "ascending"
                }
              ]
            }
          }
        },
        "2": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "smartscapeNodes \"HOST\"\n| filter matchesValue(dt.security_context,\"PAM\")\n",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "timeframe": {
            "tileTimeframe": {
              "from": "now()-4h",
              "to": "now()"
            },
            "tileTimeframeEnabled": true
          },
          "title": "Cisco_CC_Sites",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true,
            "table": {
              "columnOrder": [
                "[\"id\"]",
                "[\"lifetime\",\"start\"]",
                "[\"lifetime\",\"end\"]",
                "[\"type\"]",
                "[\"name\"]",
                "[\"dt.security_context\"]",
                "[\"tags:environment\",\"dt.cost.costcenter\"]",
                "[\"tags:environment\",\"dt.cost.product\"]",
                "[\"tags:environment\",\"Loadbalancer\"]",
                "[\"tags:environment\",\"PAM_WindowsPatchgroup\"]",
                "[\"id_classic\"]",
                "[\"os.type\"]",
                "[\"os.architecture\"]",
                "[\"os.version\"]",
                "[\"hypervisor.type\"]",
                "[\"cores\"]",
                "[\"memory\"]",
                "[\"host.mac\"]",
                "[\"host.logical.cpus\"]",
                "[\"host.physical.memory\"]",
                "[\"dt.host_group.id\"]",
                "[\"mac\"]",
                "[\"ip\"]",
                "[\"host.custom.metadata\",\"dt.cost.costcenter\"]",
                "[\"host.custom.metadata\",\"dt.cost.product\"]",
                "[\"host.custom.metadata\",\"dt.security_context\"]",
                "[\"host.additional_system_info\",\"system.architecture\"]",
                "[\"host.additional_system_info\",\"system.board.model\"]",
                "[\"host.additional_system_info\",\"system.board.serial\"]",
                "[\"host.additional_system_info\",\"system.board.vendor\"]",
                "[\"host.additional_system_info\",\"system.memory.size\"]",
                "[\"host.additional_system_info\",\"system.model\"]",
                "[\"host.additional_system_info\",\"system.processor[0].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[0].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[0].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[0].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[0].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[0].id\"]",
                "[\"host.additional_system_info\",\"system.processor[0].model\"]",
                "[\"host.additional_system_info\",\"system.processor[0].role\"]",
                "[\"host.additional_system_info\",\"system.processor[0].status\"]",
                "[\"host.additional_system_info\",\"system.processor[0].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[10].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[10].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[10].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[10].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[10].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[10].id\"]",
                "[\"host.additional_system_info\",\"system.processor[10].model\"]",
                "[\"host.additional_system_info\",\"system.processor[10].role\"]",
                "[\"host.additional_system_info\",\"system.processor[10].status\"]",
                "[\"host.additional_system_info\",\"system.processor[10].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[11].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[11].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[11].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[11].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[11].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[11].id\"]",
                "[\"host.additional_system_info\",\"system.processor[11].model\"]",
                "[\"host.additional_system_info\",\"system.processor[11].role\"]",
                "[\"host.additional_system_info\",\"system.processor[11].status\"]",
                "[\"host.additional_system_info\",\"system.processor[11].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[12].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[12].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[12].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[12].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[12].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[12].id\"]",
                "[\"host.additional_system_info\",\"system.processor[12].model\"]",
                "[\"host.additional_system_info\",\"system.processor[12].role\"]",
                "[\"host.additional_system_info\",\"system.processor[12].status\"]",
                "[\"host.additional_system_info\",\"system.processor[12].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[13].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[13].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[13].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[13].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[13].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[13].id\"]",
                "[\"host.additional_system_info\",\"system.processor[13].model\"]",
                "[\"host.additional_system_info\",\"system.processor[13].role\"]",
                "[\"host.additional_system_info\",\"system.processor[13].status\"]",
                "[\"host.additional_system_info\",\"system.processor[13].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[14].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[14].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[14].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[14].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[14].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[14].id\"]",
                "[\"host.additional_system_info\",\"system.processor[14].model\"]",
                "[\"host.additional_system_info\",\"system.processor[14].role\"]",
                "[\"host.additional_system_info\",\"system.processor[14].status\"]",
                "[\"host.additional_system_info\",\"system.processor[14].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[15].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[15].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[15].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[15].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[15].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[15].id\"]",
                "[\"host.additional_system_info\",\"system.processor[15].model\"]",
                "[\"host.additional_system_info\",\"system.processor[15].role\"]",
                "[\"host.additional_system_info\",\"system.processor[15].status\"]",
                "[\"host.additional_system_info\",\"system.processor[15].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[16].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[16].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[16].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[16].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[16].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[16].id\"]",
                "[\"host.additional_system_info\",\"system.processor[16].model\"]",
                "[\"host.additional_system_info\",\"system.processor[16].role\"]",
                "[\"host.additional_system_info\",\"system.processor[16].status\"]",
                "[\"host.additional_system_info\",\"system.processor[16].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[17].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[17].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[17].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[17].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[17].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[17].id\"]",
                "[\"host.additional_system_info\",\"system.processor[17].model\"]",
                "[\"host.additional_system_info\",\"system.processor[17].role\"]",
                "[\"host.additional_system_info\",\"system.processor[17].status\"]",
                "[\"host.additional_system_info\",\"system.processor[17].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[18].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[18].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[18].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[18].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[18].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[18].id\"]",
                "[\"host.additional_system_info\",\"system.processor[18].model\"]",
                "[\"host.additional_system_info\",\"system.processor[18].role\"]",
                "[\"host.additional_system_info\",\"system.processor[18].status\"]",
                "[\"host.additional_system_info\",\"system.processor[18].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[19].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[19].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[19].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[19].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[19].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[19].id\"]",
                "[\"host.additional_system_info\",\"system.processor[19].model\"]",
                "[\"host.additional_system_info\",\"system.processor[19].role\"]",
                "[\"host.additional_system_info\",\"system.processor[19].status\"]",
                "[\"host.additional_system_info\",\"system.processor[19].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[1].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[1].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[1].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[1].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[1].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[1].id\"]",
                "[\"host.additional_system_info\",\"system.processor[1].model\"]",
                "[\"host.additional_system_info\",\"system.processor[1].role\"]",
                "[\"host.additional_system_info\",\"system.processor[1].status\"]",
                "[\"host.additional_system_info\",\"system.processor[1].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[20].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[20].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[20].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[20].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[20].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[20].id\"]",
                "[\"host.additional_system_info\",\"system.processor[20].model\"]",
                "[\"host.additional_system_info\",\"system.processor[20].role\"]",
                "[\"host.additional_system_info\",\"system.processor[20].status\"]",
                "[\"host.additional_system_info\",\"system.processor[20].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[21].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[21].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[21].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[21].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[21].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[21].id\"]",
                "[\"host.additional_system_info\",\"system.processor[21].model\"]",
                "[\"host.additional_system_info\",\"system.processor[21].role\"]",
                "[\"host.additional_system_info\",\"system.processor[21].status\"]",
                "[\"host.additional_system_info\",\"system.processor[21].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[22].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[22].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[22].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[22].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[22].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[22].id\"]",
                "[\"host.additional_system_info\",\"system.processor[22].model\"]",
                "[\"host.additional_system_info\",\"system.processor[22].role\"]",
                "[\"host.additional_system_info\",\"system.processor[22].status\"]",
                "[\"host.additional_system_info\",\"system.processor[22].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[23].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[23].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[23].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[23].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[23].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[23].id\"]",
                "[\"host.additional_system_info\",\"system.processor[23].model\"]",
                "[\"host.additional_system_info\",\"system.processor[23].role\"]",
                "[\"host.additional_system_info\",\"system.processor[23].status\"]",
                "[\"host.additional_system_info\",\"system.processor[23].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[24].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[24].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[24].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[24].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[24].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[24].id\"]",
                "[\"host.additional_system_info\",\"system.processor[24].model\"]",
                "[\"host.additional_system_info\",\"system.processor[24].role\"]",
                "[\"host.additional_system_info\",\"system.processor[24].status\"]",
                "[\"host.additional_system_info\",\"system.processor[24].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[25].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[25].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[25].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[25].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[25].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[25].id\"]",
                "[\"host.additional_system_info\",\"system.processor[25].model\"]",
                "[\"host.additional_system_info\",\"system.processor[25].role\"]",
                "[\"host.additional_system_info\",\"system.processor[25].status\"]",
                "[\"host.additional_system_info\",\"system.processor[25].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[26].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[26].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[26].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[26].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[26].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[26].id\"]",
                "[\"host.additional_system_info\",\"system.processor[26].model\"]",
                "[\"host.additional_system_info\",\"system.processor[26].role\"]",
                "[\"host.additional_system_info\",\"system.processor[26].status\"]",
                "[\"host.additional_system_info\",\"system.processor[26].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[27].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[27].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[27].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[27].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[27].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[27].id\"]",
                "[\"host.additional_system_info\",\"system.processor[27].model\"]",
                "[\"host.additional_system_info\",\"system.processor[27].role\"]",
                "[\"host.additional_system_info\",\"system.processor[27].status\"]",
                "[\"host.additional_system_info\",\"system.processor[27].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[28].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[28].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[28].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[28].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[28].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[28].id\"]",
                "[\"host.additional_system_info\",\"system.processor[28].model\"]",
                "[\"host.additional_system_info\",\"system.processor[28].role\"]",
                "[\"host.additional_system_info\",\"system.processor[28].status\"]",
                "[\"host.additional_system_info\",\"system.processor[28].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[29].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[29].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[29].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[29].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[29].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[29].id\"]",
                "[\"host.additional_system_info\",\"system.processor[29].model\"]",
                "[\"host.additional_system_info\",\"system.processor[29].role\"]",
                "[\"host.additional_system_info\",\"system.processor[29].status\"]",
                "[\"host.additional_system_info\",\"system.processor[29].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[2].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[2].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[2].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[2].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[2].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[2].id\"]",
                "[\"host.additional_system_info\",\"system.processor[2].model\"]",
                "[\"host.additional_system_info\",\"system.processor[2].role\"]",
                "[\"host.additional_system_info\",\"system.processor[2].status\"]",
                "[\"host.additional_system_info\",\"system.processor[2].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[30].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[30].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[30].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[30].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[30].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[30].id\"]",
                "[\"host.additional_system_info\",\"system.processor[30].model\"]",
                "[\"host.additional_system_info\",\"system.processor[30].role\"]",
                "[\"host.additional_system_info\",\"system.processor[30].status\"]",
                "[\"host.additional_system_info\",\"system.processor[30].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[31].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[31].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[31].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[31].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[31].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[31].id\"]",
                "[\"host.additional_system_info\",\"system.processor[31].model\"]",
                "[\"host.additional_system_info\",\"system.processor[31].role\"]",
                "[\"host.additional_system_info\",\"system.processor[31].status\"]",
                "[\"host.additional_system_info\",\"system.processor[31].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[32].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[32].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[32].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[32].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[32].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[32].id\"]",
                "[\"host.additional_system_info\",\"system.processor[32].model\"]",
                "[\"host.additional_system_info\",\"system.processor[32].role\"]",
                "[\"host.additional_system_info\",\"system.processor[32].status\"]",
                "[\"host.additional_system_info\",\"system.processor[32].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[33].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[33].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[33].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[33].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[33].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[33].id\"]",
                "[\"host.additional_system_info\",\"system.processor[33].model\"]",
                "[\"host.additional_system_info\",\"system.processor[33].role\"]",
                "[\"host.additional_system_info\",\"system.processor[33].status\"]",
                "[\"host.additional_system_info\",\"system.processor[33].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[34].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[34].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[34].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[34].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[34].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[34].id\"]",
                "[\"host.additional_system_info\",\"system.processor[34].model\"]",
                "[\"host.additional_system_info\",\"system.processor[34].role\"]",
                "[\"host.additional_system_info\",\"system.processor[34].status\"]",
                "[\"host.additional_system_info\",\"system.processor[34].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[35].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[35].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[35].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[35].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[35].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[35].id\"]",
                "[\"host.additional_system_info\",\"system.processor[35].model\"]",
                "[\"host.additional_system_info\",\"system.processor[35].role\"]",
                "[\"host.additional_system_info\",\"system.processor[35].status\"]",
                "[\"host.additional_system_info\",\"system.processor[35].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[36].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[36].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[36].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[36].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[36].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[36].id\"]",
                "[\"host.additional_system_info\",\"system.processor[36].model\"]",
                "[\"host.additional_system_info\",\"system.processor[36].role\"]",
                "[\"host.additional_system_info\",\"system.processor[36].status\"]",
                "[\"host.additional_system_info\",\"system.processor[36].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[37].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[37].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[37].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[37].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[37].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[37].id\"]",
                "[\"host.additional_system_info\",\"system.processor[37].model\"]",
                "[\"host.additional_system_info\",\"system.processor[37].role\"]",
                "[\"host.additional_system_info\",\"system.processor[37].status\"]",
                "[\"host.additional_system_info\",\"system.processor[37].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[38].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[38].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[38].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[38].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[38].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[38].id\"]",
                "[\"host.additional_system_info\",\"system.processor[38].model\"]",
                "[\"host.additional_system_info\",\"system.processor[38].role\"]",
                "[\"host.additional_system_info\",\"system.processor[38].status\"]",
                "[\"host.additional_system_info\",\"system.processor[38].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[39].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[39].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[39].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[39].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[39].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[39].id\"]",
                "[\"host.additional_system_info\",\"system.processor[39].model\"]",
                "[\"host.additional_system_info\",\"system.processor[39].role\"]",
                "[\"host.additional_system_info\",\"system.processor[39].status\"]",
                "[\"host.additional_system_info\",\"system.processor[39].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[3].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[3].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[3].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[3].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[3].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[3].id\"]",
                "[\"host.additional_system_info\",\"system.processor[3].model\"]",
                "[\"host.additional_system_info\",\"system.processor[3].role\"]",
                "[\"host.additional_system_info\",\"system.processor[3].status\"]",
                "[\"host.additional_system_info\",\"system.processor[3].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[40].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[40].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[40].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[40].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[40].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[40].id\"]",
                "[\"host.additional_system_info\",\"system.processor[40].model\"]",
                "[\"host.additional_system_info\",\"system.processor[40].role\"]",
                "[\"host.additional_system_info\",\"system.processor[40].status\"]",
                "[\"host.additional_system_info\",\"system.processor[40].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[41].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[41].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[41].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[41].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[41].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[41].id\"]",
                "[\"host.additional_system_info\",\"system.processor[41].model\"]",
                "[\"host.additional_system_info\",\"system.processor[41].role\"]",
                "[\"host.additional_system_info\",\"system.processor[41].status\"]",
                "[\"host.additional_system_info\",\"system.processor[41].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[42].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[42].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[42].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[42].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[42].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[42].id\"]",
                "[\"host.additional_system_info\",\"system.processor[42].model\"]",
                "[\"host.additional_system_info\",\"system.processor[42].role\"]",
                "[\"host.additional_system_info\",\"system.processor[42].status\"]",
                "[\"host.additional_system_info\",\"system.processor[42].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[43].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[43].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[43].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[43].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[43].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[43].id\"]",
                "[\"host.additional_system_info\",\"system.processor[43].model\"]",
                "[\"host.additional_system_info\",\"system.processor[43].role\"]",
                "[\"host.additional_system_info\",\"system.processor[43].status\"]",
                "[\"host.additional_system_info\",\"system.processor[43].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[44].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[44].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[44].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[44].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[44].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[44].id\"]",
                "[\"host.additional_system_info\",\"system.processor[44].model\"]",
                "[\"host.additional_system_info\",\"system.processor[44].role\"]",
                "[\"host.additional_system_info\",\"system.processor[44].status\"]",
                "[\"host.additional_system_info\",\"system.processor[44].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[45].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[45].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[45].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[45].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[45].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[45].id\"]",
                "[\"host.additional_system_info\",\"system.processor[45].model\"]",
                "[\"host.additional_system_info\",\"system.processor[45].role\"]",
                "[\"host.additional_system_info\",\"system.processor[45].status\"]",
                "[\"host.additional_system_info\",\"system.processor[45].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[46].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[46].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[46].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[46].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[46].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[46].id\"]",
                "[\"host.additional_system_info\",\"system.processor[46].model\"]",
                "[\"host.additional_system_info\",\"system.processor[46].role\"]",
                "[\"host.additional_system_info\",\"system.processor[46].status\"]",
                "[\"host.additional_system_info\",\"system.processor[46].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[47].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[47].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[47].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[47].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[47].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[47].id\"]",
                "[\"host.additional_system_info\",\"system.processor[47].model\"]",
                "[\"host.additional_system_info\",\"system.processor[47].role\"]",
                "[\"host.additional_system_info\",\"system.processor[47].status\"]",
                "[\"host.additional_system_info\",\"system.processor[47].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[48].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[48].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[48].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[48].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[48].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[48].id\"]",
                "[\"host.additional_system_info\",\"system.processor[48].model\"]",
                "[\"host.additional_system_info\",\"system.processor[48].role\"]",
                "[\"host.additional_system_info\",\"system.processor[48].status\"]",
                "[\"host.additional_system_info\",\"system.processor[48].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[49].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[49].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[49].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[49].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[49].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[49].id\"]",
                "[\"host.additional_system_info\",\"system.processor[49].model\"]",
                "[\"host.additional_system_info\",\"system.processor[49].role\"]",
                "[\"host.additional_system_info\",\"system.processor[49].status\"]",
                "[\"host.additional_system_info\",\"system.processor[49].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[4].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[4].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[4].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[4].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[4].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[4].id\"]",
                "[\"host.additional_system_info\",\"system.processor[4].model\"]",
                "[\"host.additional_system_info\",\"system.processor[4].role\"]",
                "[\"host.additional_system_info\",\"system.processor[4].status\"]",
                "[\"host.additional_system_info\",\"system.processor[4].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[50].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[50].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[50].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[50].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[50].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[50].id\"]",
                "[\"host.additional_system_info\",\"system.processor[50].model\"]",
                "[\"host.additional_system_info\",\"system.processor[50].role\"]",
                "[\"host.additional_system_info\",\"system.processor[50].status\"]",
                "[\"host.additional_system_info\",\"system.processor[50].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[51].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[51].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[51].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[51].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[51].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[51].id\"]",
                "[\"host.additional_system_info\",\"system.processor[51].model\"]",
                "[\"host.additional_system_info\",\"system.processor[51].role\"]",
                "[\"host.additional_system_info\",\"system.processor[51].status\"]",
                "[\"host.additional_system_info\",\"system.processor[51].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[52].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[52].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[52].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[52].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[52].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[52].id\"]",
                "[\"host.additional_system_info\",\"system.processor[52].model\"]",
                "[\"host.additional_system_info\",\"system.processor[52].role\"]",
                "[\"host.additional_system_info\",\"system.processor[52].status\"]",
                "[\"host.additional_system_info\",\"system.processor[52].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[53].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[53].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[53].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[53].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[53].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[53].id\"]",
                "[\"host.additional_system_info\",\"system.processor[53].model\"]",
                "[\"host.additional_system_info\",\"system.processor[53].role\"]",
                "[\"host.additional_system_info\",\"system.processor[53].status\"]",
                "[\"host.additional_system_info\",\"system.processor[53].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[54].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[54].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[54].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[54].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[54].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[54].id\"]",
                "[\"host.additional_system_info\",\"system.processor[54].model\"]",
                "[\"host.additional_system_info\",\"system.processor[54].role\"]",
                "[\"host.additional_system_info\",\"system.processor[54].status\"]",
                "[\"host.additional_system_info\",\"system.processor[54].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[55].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[55].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[55].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[55].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[55].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[55].id\"]",
                "[\"host.additional_system_info\",\"system.processor[55].model\"]",
                "[\"host.additional_system_info\",\"system.processor[55].role\"]",
                "[\"host.additional_system_info\",\"system.processor[55].status\"]",
                "[\"host.additional_system_info\",\"system.processor[55].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[56].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[56].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[56].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[56].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[56].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[56].id\"]",
                "[\"host.additional_system_info\",\"system.processor[56].model\"]",
                "[\"host.additional_system_info\",\"system.processor[56].role\"]",
                "[\"host.additional_system_info\",\"system.processor[56].status\"]",
                "[\"host.additional_system_info\",\"system.processor[56].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[57].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[57].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[57].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[57].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[57].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[57].id\"]",
                "[\"host.additional_system_info\",\"system.processor[57].model\"]",
                "[\"host.additional_system_info\",\"system.processor[57].role\"]",
                "[\"host.additional_system_info\",\"system.processor[57].status\"]",
                "[\"host.additional_system_info\",\"system.processor[57].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[58].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[58].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[58].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[58].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[58].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[58].id\"]",
                "[\"host.additional_system_info\",\"system.processor[58].model\"]",
                "[\"host.additional_system_info\",\"system.processor[58].role\"]",
                "[\"host.additional_system_info\",\"system.processor[58].status\"]",
                "[\"host.additional_system_info\",\"system.processor[58].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[59].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[59].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[59].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[59].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[59].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[59].id\"]",
                "[\"host.additional_system_info\",\"system.processor[59].model\"]",
                "[\"host.additional_system_info\",\"system.processor[59].role\"]",
                "[\"host.additional_system_info\",\"system.processor[59].status\"]",
                "[\"host.additional_system_info\",\"system.processor[59].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[5].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[5].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[5].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[5].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[5].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[5].id\"]",
                "[\"host.additional_system_info\",\"system.processor[5].model\"]",
                "[\"host.additional_system_info\",\"system.processor[5].role\"]",
                "[\"host.additional_system_info\",\"system.processor[5].status\"]",
                "[\"host.additional_system_info\",\"system.processor[5].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[60].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[60].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[60].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[60].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[60].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[60].id\"]",
                "[\"host.additional_system_info\",\"system.processor[60].model\"]",
                "[\"host.additional_system_info\",\"system.processor[60].role\"]",
                "[\"host.additional_system_info\",\"system.processor[60].status\"]",
                "[\"host.additional_system_info\",\"system.processor[60].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[61].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[61].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[61].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[61].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[61].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[61].id\"]",
                "[\"host.additional_system_info\",\"system.processor[61].model\"]",
                "[\"host.additional_system_info\",\"system.processor[61].role\"]",
                "[\"host.additional_system_info\",\"system.processor[61].status\"]",
                "[\"host.additional_system_info\",\"system.processor[61].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[62].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[62].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[62].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[62].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[62].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[62].id\"]",
                "[\"host.additional_system_info\",\"system.processor[62].model\"]",
                "[\"host.additional_system_info\",\"system.processor[62].role\"]",
                "[\"host.additional_system_info\",\"system.processor[62].status\"]",
                "[\"host.additional_system_info\",\"system.processor[62].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[63].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[63].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[63].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[63].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[63].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[63].id\"]",
                "[\"host.additional_system_info\",\"system.processor[63].model\"]",
                "[\"host.additional_system_info\",\"system.processor[63].role\"]",
                "[\"host.additional_system_info\",\"system.processor[63].status\"]",
                "[\"host.additional_system_info\",\"system.processor[63].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[64].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[64].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[64].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[64].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[64].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[64].id\"]",
                "[\"host.additional_system_info\",\"system.processor[64].model\"]",
                "[\"host.additional_system_info\",\"system.processor[64].role\"]",
                "[\"host.additional_system_info\",\"system.processor[64].status\"]",
                "[\"host.additional_system_info\",\"system.processor[64].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[65].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[65].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[65].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[65].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[65].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[65].id\"]",
                "[\"host.additional_system_info\",\"system.processor[65].model\"]",
                "[\"host.additional_system_info\",\"system.processor[65].role\"]",
                "[\"host.additional_system_info\",\"system.processor[65].status\"]",
                "[\"host.additional_system_info\",\"system.processor[65].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[66].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[66].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[66].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[66].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[66].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[66].id\"]",
                "[\"host.additional_system_info\",\"system.processor[66].model\"]",
                "[\"host.additional_system_info\",\"system.processor[66].role\"]",
                "[\"host.additional_system_info\",\"system.processor[66].status\"]",
                "[\"host.additional_system_info\",\"system.processor[66].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[67].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[67].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[67].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[67].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[67].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[67].id\"]",
                "[\"host.additional_system_info\",\"system.processor[67].model\"]",
                "[\"host.additional_system_info\",\"system.processor[67].role\"]",
                "[\"host.additional_system_info\",\"system.processor[67].status\"]",
                "[\"host.additional_system_info\",\"system.processor[67].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[68].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[68].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[68].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[68].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[68].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[68].id\"]",
                "[\"host.additional_system_info\",\"system.processor[68].model\"]",
                "[\"host.additional_system_info\",\"system.processor[68].role\"]",
                "[\"host.additional_system_info\",\"system.processor[68].status\"]",
                "[\"host.additional_system_info\",\"system.processor[68].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[69].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[69].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[69].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[69].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[69].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[69].id\"]",
                "[\"host.additional_system_info\",\"system.processor[69].model\"]",
                "[\"host.additional_system_info\",\"system.processor[69].role\"]",
                "[\"host.additional_system_info\",\"system.processor[69].status\"]",
                "[\"host.additional_system_info\",\"system.processor[69].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[6].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[6].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[6].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[6].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[6].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[6].id\"]",
                "[\"host.additional_system_info\",\"system.processor[6].model\"]",
                "[\"host.additional_system_info\",\"system.processor[6].role\"]",
                "[\"host.additional_system_info\",\"system.processor[6].status\"]",
                "[\"host.additional_system_info\",\"system.processor[6].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[70].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[70].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[70].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[70].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[70].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[70].id\"]",
                "[\"host.additional_system_info\",\"system.processor[70].model\"]",
                "[\"host.additional_system_info\",\"system.processor[70].role\"]",
                "[\"host.additional_system_info\",\"system.processor[70].status\"]",
                "[\"host.additional_system_info\",\"system.processor[70].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[71].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[71].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[71].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[71].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[71].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[71].id\"]",
                "[\"host.additional_system_info\",\"system.processor[71].model\"]",
                "[\"host.additional_system_info\",\"system.processor[71].role\"]",
                "[\"host.additional_system_info\",\"system.processor[71].status\"]",
                "[\"host.additional_system_info\",\"system.processor[71].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[72].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[72].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[72].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[72].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[72].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[72].id\"]",
                "[\"host.additional_system_info\",\"system.processor[72].model\"]",
                "[\"host.additional_system_info\",\"system.processor[72].role\"]",
                "[\"host.additional_system_info\",\"system.processor[72].status\"]",
                "[\"host.additional_system_info\",\"system.processor[72].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[73].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[73].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[73].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[73].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[73].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[73].id\"]",
                "[\"host.additional_system_info\",\"system.processor[73].model\"]",
                "[\"host.additional_system_info\",\"system.processor[73].role\"]",
                "[\"host.additional_system_info\",\"system.processor[73].status\"]",
                "[\"host.additional_system_info\",\"system.processor[73].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[74].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[74].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[74].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[74].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[74].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[74].id\"]",
                "[\"host.additional_system_info\",\"system.processor[74].model\"]",
                "[\"host.additional_system_info\",\"system.processor[74].role\"]",
                "[\"host.additional_system_info\",\"system.processor[74].status\"]",
                "[\"host.additional_system_info\",\"system.processor[74].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[7].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[7].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[7].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[7].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[7].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[7].id\"]",
                "[\"host.additional_system_info\",\"system.processor[7].model\"]",
                "[\"host.additional_system_info\",\"system.processor[7].role\"]",
                "[\"host.additional_system_info\",\"system.processor[7].status\"]",
                "[\"host.additional_system_info\",\"system.processor[7].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[8].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[8].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[8].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[8].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[8].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[8].id\"]",
                "[\"host.additional_system_info\",\"system.processor[8].model\"]",
                "[\"host.additional_system_info\",\"system.processor[8].role\"]",
                "[\"host.additional_system_info\",\"system.processor[8].status\"]",
                "[\"host.additional_system_info\",\"system.processor[8].vendor\"]",
                "[\"host.additional_system_info\",\"system.processor[9].cache.l2.size\"]",
                "[\"host.additional_system_info\",\"system.processor[9].cache.l3.size\"]",
                "[\"host.additional_system_info\",\"system.processor[9].cores.physical\"]",
                "[\"host.additional_system_info\",\"system.processor[9].cores.virtual\"]",
                "[\"host.additional_system_info\",\"system.processor[9].frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor[9].id\"]",
                "[\"host.additional_system_info\",\"system.processor[9].model\"]",
                "[\"host.additional_system_info\",\"system.processor[9].role\"]",
                "[\"host.additional_system_info\",\"system.processor[9].status\"]",
                "[\"host.additional_system_info\",\"system.processor[9].vendor\"]",
                "[\"host.additional_system_info\",\"system.vendor\"]",
                "[\"host.additional_system_info\",\"system.processor.frequency.max\"]",
                "[\"host.additional_system_info\",\"system.processor.frequency.min\"]",
                "[\"host.additional_system_info\",\"system.processor.model\"]",
                "[\"host.additional_system_info\",\"system.serial\"]",
                "[\"dt.cost.costcenter\"]",
                "[\"dt.cost.product\"]",
                "[\"host.name\"]",
                "[\"aws.resource.id\"]",
                "[\"aws.account.id\"]",
                "[\"aws.availability_zone\"]",
                "[\"cloud.provider\"]",
                "[\"aws.arn\"]",
                "[\"private_ip_address\"]",
                "[\"aws.region\"]",
                "[\"private_dns_name\"]",
                "[\"hasPublicTraffic\"]",
                "[\"host.ip\"]",
                "[\"host.has_public_traffic\"]"
              ],
              "columnWidths": {
                "[\"cisco_cc.cc_site_link\"]": 219,
                "[\"cisco_cc.parent_site_id\"]": 197.9,
                "[\"cisco_cc.site_name_hierarchy\"]": 219.8,
                "[\"dt.security_context\"]": 182.59,
                "[\"id_classic\"]": 148.4,
                "[\"troubleshooting.upsert_source\"]": 436.8
              },
              "sortBy": [
                {
                  "columnId": "[\"id\"]",
                  "direction": "ascending"
                }
              ]
            }
          }
        },
        "3": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "smartscapeNodes EXT_NETWORK_DEVICE\n| fieldsAdd type, dt.security_context\n| traverse { belongs_to }, { EXT_NETWORK_INTERFACE }, direction:\"backward\", fieldsKeep: { id, name, description, dt.security_context}\n| traverse { calls }, { EXT_NETWORK_INTERFACE }, direction:\"forward\", fieldsKeep: { id, name }\n| traverse { belongs_to}, { EXT_NETWORK_DEVICE }, direction:\"forward\", fieldsKeep: { id, name }\n| fields\n    type,\n    dt.security_context,\n    base.device=record(id=id, name=name),\n    base.interface=record(id=dt.traverse.history[2][id], name=dt.traverse.history[2][name]),\n    connection=\"   ⬅️   \",\n    neighbor.interface=record(id=dt.traverse.history[1][id], name=dt.traverse.history[1][name]),\n    neighbor.device=record(id=dt.traverse.history[0][id], name=dt.traverse.history[0][name]),\n    neighbor.security=record(id=dt.traverse.history[0][id], name=dt.traverse.history[0][dt.security_context])\n",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "title": "",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true,
            "table": {
              "columnWidths": {
                "[\"neighbor.security\",\"name\"]": 92.8,
                "[\"type\"]": 172
              },
              "sortBy": [
                {
                  "columnId": "[\"type\"]",
                  "direction": "ascending"
                }
              ]
            }
          }
        },
        "4": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "smartscapeNodes \"*\",from:-4h,to:now()\n| summarize by:{type},count()",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "timeframe": {
            "tileTimeframe": {
              "from": "now()-4h",
              "to": "now()"
            },
            "tileTimeframeEnabled": false
          },
          "title": "",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true,
            "table": {
              "sortBy": [
                {
                  "columnId": "[\"type\"]",
                  "direction": "descending"
                }
              ]
            }
          }
        },
        "5": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "smartscapeNodes \"NETWORK_INTERFACE\"",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "title": "",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true,
            "table": {
              "sortBy": [
                {
                  "columnId": "[\"id\"]",
                  "direction": "ascending"
                }
              ]
            }
          }
        },
        "6": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "fetch `dt.entity.network:device`\n| fieldsAdd dt.security_context, managementZones\n",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "title": "",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true,
            "table": {
              "columnWidths": {
                "[\"id\"]": 281.4
              }
            }
          }
        },
        "7": {
          "davis": {
            "davisVisualization": {
              "isAvailable": true
            },
            "enabled": false
          },
          "query": "fetch `dt.entity.cisco_cc:site`\n| fieldsAdd entity.name,level_01_name,level_02_name, level_03_name,dt.security_context",
          "querySettings": {
            "defaultSamplingRatio": 10,
            "defaultScanLimitGbytes": 500,
            "enableSampling": false,
            "maxResultMegaBytes": 1,
            "maxResultRecords": 1000
          },
          "title": "",
          "type": "data",
          "visualization": "table",
          "visualizationSettings": {
            "autoSelectVisualization": true
          }
        }
      },
      "variables": [],
      "version": 21
    })
  private = true
}
